### ISSUE TITLE
 hysteria是否支持NGINX 的 SNI分流？

### ISSUE THREAD

**Issue by onlyJinx** [HyNetwork/hysteria#103]
Hello,

我使用下面的配置，可以正常的使用sni分流给trojan-gfw和x2ray，把tls部分交给他们处理，但是我是用同样的方法分流给hysteria却无法使用，服务端没有任何输出，请问找个要怎么处理，因为我想要的是nginx监听443然后分流给各种代理工具。
```
...
stream {
    map $ssl_preread_server_name $name {
        xxxxxx.com 127.0.0.1:7001;  #hysteria监听端口
        default 127.0.0.1:4433;
    }
    server {
        listen 443 reuseport;
        listen [::]:443 reuseport;
        proxy_pass $name;
        ssl_preread on;
    }
}
...
```

**Comment by tobyxdd** [comment]
hysteria 根本不是基于 TCP 的协议，你用 nginx 分流完全不可能行得通

**Comment by yuanyiwei** [comment]
> hysteria 根本不是基于 TCP 的协议，你用 nginx 分流完全不可能行得通

nginx 现在有 quic 分支了（ https://hg.nginx.org/nginx-quic/ ）

**Comment by tobyxdd** [comment]
nginx 支持 quic 也不支持 quic 回源，支持 quic 回源也不会支持 hysteria 版的 quic，抛弃幻想吧

**Comment by yuanyiwei** [comment]
> 这个方法可靠吗，我想通过域名路径分流。

感觉没什么用，对hy2是直接流转发了
