### ISSUE TITLE
Can't run as server on Asus router RT-AC86U

### ISSUE THREAD

**Issue by samho1234567** [HyNetwork/hysteria#105]
Hello. I have successfully set up [Xray](https://github.com/XTLS/Xray-core) and [Brook](https://github.com/txthinking/brook) servers on my Asus router RT-AC86U, but failed to set up hysteria server.

![hysteria error message](https://user-images.githubusercontent.com/8604017/128533106-941546a1-70b5-447e-8003-df2bbd80d4ee.png)

The error message prompts:
`error while loading shared libraries: libpthread.so.0: cannot open shared object file: No such file or directory`

---

In fact, `libpthread.so.0` exists in `/lib/` directory.

![libpthread.so.0](https://user-images.githubusercontent.com/8604017/128535040-091043ff-2dfb-43f9-a70d-56d365824ae2.png)

**Comment by tobyxdd** [comment]
应该是系统 libc 版本问题。我后面会出一个取消 tun 支持的版本（就不需要 CGO, 也就没有 libc 依赖了 是纯静态 binary）

**Comment by samho1234567** [comment]
好的，谢谢

**Comment by tobyxdd** [comment]
https://github.com/HyNetwork/hysteria/releases/tag/v0.8.4

Try the notun versions

**Comment by samho1234567** [comment]
测试成功，谢谢
