### ISSUE TITLE
mipsle 二进制文件无法运行

### ISSUE THREAD

**Issue by ss916** [HyNetwork/hysteria#106]
下载预编译二进制文件 https://github.com/HyNetwork/hysteria/releases/download/v0.8.3/hysteria-linux-mipsle
在mipsle架构路由器上运行
./hysteria-linux-mipsle -h

报错提示：
-sh: ./hysteria-linux-mipsle: not found

**Comment by ss916** [comment]
hysteria-linux-arm64 同样有这个问题，无法运行。
目前测试只有hysteria-linux-amd64版正常运行

**Comment by tobyxdd** [comment]
应该是系统 libc 版本问题。我后面会出一个取消 tun 支持的版本（就不需要 CGO, 也就没有 libc 依赖了 是纯静态 binary）

**Comment by tobyxdd** [comment]
https://github.com/HyNetwork/hysteria/releases/tag/v0.8.4

**Comment by ss916** [comment]
hysteria-notun-linux-amd64
hysteria-notun-linux-arm64
hysteria-notun-linux-mipsle
都能正常工作了。感谢开发者！
