### ISSUE TITLE
无法使用bash启动该程序

### ISSUE THREAD

**Issue by ajdgsu** [HyNetwork/hysteria#109]
我知道可以使用./运行程序，但我想要让它在openwrt上运行，然而openwrt貌似默认会强制使用ash(busybox里的命令，等同于sh)来运行所有指令(包括/bin和/sbin里面的程序都是通过ash调用的)，因此使用./会调用ash(等同于sh)会报错   syntax error: unexpected "(" ；因此最好的方法是使用bash，然而bash会报错 cannot execute binary file(即使文件已经777了，而且在其他linux系统上测试bash运行程序也是同样结果)

**Comment by tobyxdd** [comment]
试下 notun 版本

**Comment by haruue** [comment]
这个 Issue 关闭有段时间了，不过我还是解答一下。

遇到这个问题是你下载了错误架构的可执行文件， ash 遇到无法识别的架构 ELF 会当作脚本执行， 自然就
```
line 1: syntax error: unexpected word (expecting ")")
```
请先确定你的路由器架构，在网上搜索你的路由器型号是个好办法。

另外使用 bash 运行二进制文件不是 `bash 二进制文件名称` ，这是执行 bash 脚本的方法。所以会输出一行 `cannot execute binary file` 。
