### ISSUE TITLE
hysteria 客户端运行一段时间后产生大量 udp6 监听

### ISSUE THREAD

**Issue by rampageX** [HyNetwork/hysteria#113]
此时代理工作仍然正常

![2021-08-13_204845](https://user-images.githubusercontent.com/994081/129359637-dc6bab7d-3a88-4915-aeed-300c50ec85f5.jpg)

```
netstat -lnp | grep hysteria | wc -l
69
```

Hysteria 运行在 N1 盒子 Armbian 上，系统通过 sysctl.conf 禁用了 ipv6 协议：

```
#disable ipv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
```

**Comment by tobyxdd** [comment]
这是 SOCKS5 UDP 转发吧，有什么问题吗？

**Comment by rampageX** [comment]
> 这是 SOCKS5 UDP 转发吧，有什么问题吗？

因为这个监听数量在不断上涨而且一直下不来，看到过 200 多的，线路没有ipv6，系统已经禁用了 ipv6， 为何在 udp6 上会跑这么多？ 如果软件设计如此，可以关闭。

**Comment by haruue** [comment]
同时监听 IPv4 和 IPv6 在 netstat 会显示成监听 IPv6， 因为 [所有 IPv4 地址都被映射为 IPv6 地址](https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses)。 之前还有人报告说 hysteria 服务端只监听了 IPv6 而没有监听 IPv4 却能正常使用，一样的问题。
UDP 监听多少根据所代理的程序决定。 200 其实不算多的，不影响正常使用就没问题。
