### ISSUE TITLE
Message Buffer Size error

### ISSUE THREAD

**Issue by moien007** [HyNetwork/hysteria#115]
Hi, this line's frequently seen in the logs that hysteria emits...

```text
wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
```

Anything I should do about it?

**Comment by tobyxdd** [comment]
Does it prevent Hysteria from working properly? Also, what is the MTU of your network interface?

**Comment by tobyxdd** [comment]
It would be best if you could provide the full log. Remember to remove sensitive information like server credentials.

**Comment by moien007** [comment]
> Does it prevent Hysteria from working properly? Also, what is the MTU of your network interface?

Yes, it works. My MTU on client's side is the traditional 1500; not sure about server.

> It would be best if you could provide the full log. Remember to remove sensitive information like server credentials.

Client's logs are messed up (I'm on Windows as you can tell)

![hysteria-log](https://user-images.githubusercontent.com/14028665/130016377-6173b08f-3e9d-43ce-ab51-b40f6b386b3f.PNG)

**Comment by tobyxdd** [comment]
Try turning on the new `disable_mtu_discovery` option added in v0.8.5 (on both the server and client)

**Comment by moien007** [comment]
> Try turning on the new `disable_mtu_discovery` option added in v0.8.5 (on both the server and client)

Sorry, I've removed hysteria.
