### ISSUE TITLE
服务端启动报错

### ISSUE THREAD

**Issue by Aniark** [HyNetwork/hysteria#122]
报错内容如下
`[FATA] [file:./config.json] [error:invalid cha
racter '/' after object key:value pair] Failed to parse server configura
tion`

检查了一遍json，确定我key的路径没有填错
又分别测试了ecc和rsa两种证书，依然无法解决

**Comment by tobyxdd** [comment]
JSON 格式有问题

**Comment by Aniark** [comment]
我是原样复制readme中的json，只改动了域名，邮箱，证书

`{
  "listen": ":36712", // Listen address
  "acme": {
    "domains": [
      "domain.com"
    ], // Domains for the ACME cert
    "email": "mail@mail.com", // Registration email, optional but recommended
    "disable_http": false, // Disable HTTP challenges
    "disable_tlsalpn": false, // Disable TLS-ALPN challenges
    "alt_http_port": 8080, // Alternate port for HTTP challenges
    "alt_tlsalpn_port": 4433 // Alternate port for TLS-ALPN challenges
  },
  "cert": "/root/.acme.sh/domain.com/fullchain.cer", // Cert file, mutually exclusive with the ACME options above
  "key": "/root/.acme.sh/domain.com/domain.com.key", // Key file, mutually exclusive with the ACME options above
  "up_mbps": 100, // Max upload Mbps per client
  "down_mbps": 100, // Max download Mbps per client
  "disable_udp": false, // Disable UDP support
  "acl": "my_list.acl", // See ACL below
  "obfs": "AMOGUS", // Obfuscation password
  "auth": { // Authentication
    "mode": "password", // Mode, supports "password`

**Comment by Aniark** [comment]
{
  "listen": ":36712",
  "cert": "/home/ubuntu/my.crt",
  "key": "/home/ubuntu/my.key",
  "obfs": "fuck me till the daylight",
  "up_mbps": 100,
  "down_mbps": 100
}

使用readme里的这段配置，解决了报错问题
