### ISSUE TITLE
希望加入grpc的serviceName功能

### ISSUE THREAD

**Issue by ajdgsu** [HyNetwork/hysteria#123]
简单来说这个功能就是配合nginx的location指令使用的，可以非常方便的把流量代理到不同端口从而实现443端口跑数据防qos

可以参考一下这个自动脚本实现的例子 https://github.com/mack-a/v2ray-agent (下面为它的部分配置)

![Screenshot_20210830-231134_JuiceSSH](https://user-images.githubusercontent.com/45306865/131362339-ddd7de21-d4c4-4c40-be36-35a65e0a7de9.jpg)
![Screenshot_20210830-231328_JuiceSSH](https://user-images.githubusercontent.com/45306865/131362350-130af73e-f790-4719-b107-4966ffc4e89e.jpg)

**Comment by mritd** [comment]
hysteria 是在基于 UDP 的 QUIC 基础上实现的。

**Comment by tobyxdd** [comment]
Hysteria 是 UDP 的，根本不可能支持 nginx 转发
