### ISSUE TITLE
Format limit of "obfs" configuration may exist as clients could not establish connection to server.

### ISSUE THREAD

**Issue by cky1201** [HyNetwork/hysteria#125]
There could be a hidden limitation on what could be set as a valid string in "obfs". 

Running Hysteria 0.8.5 server, "obfs": "CfZYtJ4qK6iRg2Oy" is not a valid string even no error will be shown, 
while "vLol0IfviMCXutUe" is a valid one. 

Due to personal issues I could not try a lot of strings to verify this claim, and would like to see if similar issues occur among active users. Thank you.

P.S. Strings generated by command:
`openssl rand -base64 12`
.

**Comment by tobyxdd** [comment]
Mind giving me a little more detail? I tried the two strings you provided as well as a few others I generated myself but didn't have any problems.

**Comment by cky1201** [comment]
Thank you for your kind reply.

The issue occurred when using hysteria-plugin 0.8.5 in Segarnet. 
When the aforementioned obfs parameter was put in, client software indicated that was a "connection closed" while server does not generate any log. 

Issue would resolve once parameter changes. Meanwhile server would generate corresponding log matching client's requests. 

I would be submitting this issue to developer(s) of Hysteria-plugin if you had confirmed that such issue could not be reproduced in your environment.
