### ISSUE TITLE
可否调整几个文件，以方便做插件整合

### ISSUE THREAD

**Issue by dev4u** [HyNetwork/hysteria#131]
cmd目录下server、client、config、acme这四个文件，可否调整他们不要用main这个包名？我想整合成插件，很不好操作。

**Comment by tobyxdd** [comment]
Go 要编译可执行程序就得要 main 包名啊，这个怎么可能改。你要做整合插件是做成什么形式的？

**Comment by dev4u** [comment]
是需要main包名，所以cmd/main.go这个文件的包名可以保持不变。
创建hysteria的服务，需要cmd下的server、client、……相关代码。现在这些代码都一并放在main包下，没办法重用。

**Comment by tobyxdd** [comment]
理论上有 pkg 里的代码就足够组成 hysteria 的所有功能了，cmd 里的 server client 只是读取配置然后调用。你是想复用 cmd 里的哪些东西

**Comment by dev4u** [comment]
我其实是想套在hysteria里面做传输，就像cloak-plugin、v2ray-plugin那样。

**Comment by tobyxdd** [comment]
具体是什么意思？你是想给什么东西做 plugin 呢
