### ISSUE TITLE
能否稍微完善一下docker镜像的说明，谢谢

### ISSUE THREAD

**Issue by qnxsgwy** [HyNetwork/hysteria#132]
想用docker运行，目前docker只有一个镜像，没有任何说明，能否稍微完善一下说明，config.json应该挂载到哪个目录这些，谢谢。

**Comment by Error996** [comment]
可执行程序在docker中的/usr/local/bin/hysteria，配置文件你自己随便映射啊，反正是可以带参数指定，比如
/usr/local/bin/hysteria -config /root/config.json client(server)

**Comment by tobyxdd** [comment]
@mritd 考虑加个 docker 的说明么？

**Comment by mritd** [comment]
好的，我下午处理一下

**Comment by mritd** [comment]
@qnxsgwy docker 使用文档已经合并到了 master
