### ISSUE TITLE
请问如何转发hysteria的流量？

### ISSUE THREAD

**Issue by wholenewx** [HyNetwork/hysteria#133]
您好 开发者

向您请教个关于转发的问题：

在地球的另一边有一台服务器，若直接ss连接的话是几乎连不上的状态，通过kcptun直连的话属于勉强能用，若通过亚洲机房中转的话速度还行，是这样中转的：

ss客户端 --》 本地kcptun client ------》 亚洲机房kcptun server --》同台机器kcptun client ------》 地球另一边的kcptun server --》 ss服务端

这样中转之后的速度是没有中转的四倍有余（所有的kcptun都只设置了fast=2）

现在换上了hysteria，直连的速度就差不多能和通过kcptun中转的速度打个平手，厉害厉害！

下载速度能差不多打平的时候，延时还是差了很多，SagerNet app上通过kcptun中转的https握手耗时最低是600多ms，一般都在700多到900多ms之间；hysteria直连的耗时最低900多ms，而大部分时候都在1500ms以上

另外，现在能达到的速度毕竟离本地速度的极限以及中转机房和目标机房的速度上限都还很远，从追求更好的网络体验来说，现在就在想怎么中转hysteria的流量

因为是通过域名连接的，所以一下子不知道如何在保证证书正确的情况下去转发。而且hysteria服务端的设置跟kcptun也完全不一样，不知该如何下手

如果无视证书直接在客户端用亚洲机房的IP去连的话，数据包到亚洲机房的时候是直接用firewalld的流量转发去地球另一边的机器还是通过自身服务端接收后转发去目标机器？或者用gost之类的软件？追求速度的前提下哪种更好？如果是服务端接收后转发的话config.json应该怎么写？目前有这样的功能吗？

另外在安装测试的时候我发现如果无视证书错误的话，下载速度是更快一点的（服务端指定了有效证书，客户端在设置的时候习惯性的写的IP而不是域名），所以我有个建议：能不能在以IP去连接的情况下不需要证书，服务端也不用设置证书，采用其他能最低限度保证数据安全（不能被解密成明文就行）的方式？类似于ss那种AES-256-GCM的方式？（本人不是程序员，如果这个建议很蠢您就直接无视吧）

如何转发您先给我一点建议吧

谢谢

**Comment by Error996** [comment]
简单办法，不要用除了基于tls协议以外的任何协议

**Comment by wholenewx** [comment]
> 简单办法，不要用除了基于tls协议以外的任何协议

没有看懂，用“基于TLS的协议”去转发？怎么操作？

**Comment by tobyxdd** [comment]
配置里有个 `server_name` 可以用来处理这种情况，写转发服务器的 IP 但 `server_name` 写证书原域名。

至于怎么转发，只要能双向转发 UDP 包的方案都是可以的，对 hysteria 本身没有区别。性能只能你自己比较了

**Comment by tobyxdd** [comment]
忽略证书错误速度变快应该只是你的测试误差，忽略不忽略都是一样的加密。hysteria 用的 TLS 1.3 cipher suites 本来也就是 AES 或者 ChaCha20

**Comment by wholenewx** [comment]
实验下来，gost无法转发hysteria的流量，反正用这个命令转发不成功：

gost -L=:12345 -F=quic://10.20.30.40:6789

firewallD可以转发，但是总觉得“响应”很慢，而且速度很不稳定，满速和龟速之间波动，不如kcptun client --》 kcptun server --》kcptun client --》 kcptun server的表现稳定

希望能增加一个功能：除了作为客户端和服务端，也可以作为中转服务器存在
