### ISSUE TITLE
可否支持出站配置

### ISSUE THREAD

**Issue by cncherisher** [HyNetwork/hysteria#135]
由于vps的ip被送中，目前采用的方案是使用cloudflare warp的linux客户端配合v2ray的outbound，使google和youtube的流量走warp的socks5隧道，不知道hysteria可否支持类似配置

**Comment by cncherisher** [comment]
个人觉得这个项目能够合并到v2ray的quic传输就完美了（

**Comment by lxhao61** [comment]
> 个人觉得这个项目能够合并到v2ray的quic传输就完美了（

是的

**Comment by pty819** [comment]
> 个人觉得这个项目能够合并到v2ray的quic传输就完美了（

v2ray的quic年久失修，假如被替换为hysteria可谓如虎添翼

**Comment by emptysuns** [comment]
感谢开发者的贡献。

outbound 是个很好的优化建议，期待支持

**Comment by tobyxdd** [comment]
https://github.com/HyNetwork/hysteria/issues/172
