### ISSUE TITLE
可以把client速度设的比宽带速度低一些吗？

### ISSUE THREAD

**Issue by Azuresonance** [HyNetwork/hysteria#146]
我的client是一个中转站，会把hysteria的连接转发给一个shadosocks server
大致意思是这样：

hysteria server <-----> hysteria client+shadowsocks server <-------> shadowsocks client

在这种情况下，我把hysteria client的速度设为最大宽带速度似乎不太合适，因为会影响shadowsocks那边的速度。
设成宽带速度的一般，hysteria能正常工作吗？

**Comment by tobyxdd** [comment]
当然没问题，只要不高于就行
