### ISSUE TITLE
服务器端似乎不会定期读取证书

### ISSUE THREAD

**Issue by weijarz** [HyNetwork/hysteria#148]
前几天client启动失败，一直报这个错误，一直没想明白问题在哪，以前好好的。

Nov 16 07:57:35 pc hysteria-linux-amd64[1091]: 2021-11-16T07:57:35+08:00 [FATA] [error:CRYPTO_ERROR (0x12a): x509: certificate has expired or is not yet valid: current time 2021-11-16T07:57:35+08:00 is after 2021-11-11T23:56:11Z] Failed to initialize client

今天突然想起来，我的证书是用let‘s encrypt签的，只有三个月有效期，现在已经过期了，重启一下服务器端又可以工作了。

**Comment by jaywongs** [comment]
@tobyxdd  This problem has recurred again.

**Comment by tobyxdd** [comment]
> @tobyxdd This problem has recurred again.

Fixed in c4993f8dd1c0e54599d39706dc0a71a5fb51d725
