### ISSUE TITLE
Could you add a command to let hysteria run in the background

### ISSUE THREAD

**Issue by quaggalinux** [HyNetwork/hysteria#158]
Could you add a command to let hysteria run in the background like Caddy's command "start".

That command will be useful for windows CMD run hysteria.

Thanks

**Comment by haruue** [comment]
When I was young (10+ years ago), I used this VBScript to run any command-line program in the background without an ugly black window.

```vbs
set ws=wscript.createobject("wscript.shell")
ws.run "hysteria.exe",0
```

Hope this still works on Windows 10/11.
