### ISSUE TITLE
Can I have a client for windows and Mac OS as well?

### ISSUE THREAD

**Issue by abcdef123ghi** [HyNetwork/hysteria#159]
Hi can I have a client for windows and Mac OS as well，how do I use docker, can you give me a example within the document? 
（有win和Mac 客户端？另外 docker 怎样使用也不清楚）

**Comment by tobyxdd** [comment]
Not sure what you mean but it already works on Windows and macOS.

If you want a GUI, we have no plans to develop it yet. Consider contacting authors of existing tools for hysteria support.
