### ISSUE TITLE
可以详细说说acl里的hijack用法吗

### ISSUE THREAD

**Issue by yaotthaha** [HyNetwork/hysteria#160]
可以将连接劫持到本地（服务端）socks5吗

**Comment by tobyxdd** [comment]
感觉你理解错了 hijack 的意思。hijack 是将匹配到的连接的 target 劫持到另一个指定的地址。例如 hijack ip 8.8.8.8 1.1.1.1 是把到 8.8.8.8 的连接劫持到 1.1.1.1

**Comment by yaotthaha** [comment]
哦哦，我误解了。hysteria的quic速度很快，希望可以加上出站代理，这样就可以配合*ray的路由功能
