### ISSUE TITLE
go install error

### ISSUE THREAD

**Issue by bhzhu203** [HyNetwork/hysteria#162]
go get github.com/HyNetwork/hysteria
go get: github.com/HyNetwork/hysteria@v0.8.6: parsing go.mod:
	module declares its path as: github.com/tobyxdd/hysteria
	        but was required as: github.com/HyNetwork/hysteria

by the way,can not build  hysteria without -ldflags "-w -s"

go build without -ldflags "-w -s" will lead to fail . Please update Doc 

go build -o hysteria1 ./cmd
"# github.com/tobyxdd/hysteria/cmd"
/home/bhzhu/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-build3574215657/b001/exe/a.out: final close failed: Invalid operation
collect2: error: ld returned 1 exit status

successed:
go build -o hysteria -ldflags "-w -s" ./cmd

Env:
Linux LFS
glib 2.26.20160125
gcc 10.2.0

**Comment by haruue** [comment]
I cannot reproduce this bug in any linux distro I have. 
It seems like bugs in the binutils (the project provides the ld).
Could you please check the version of binutils with `ld --version`

**Comment by bhzhu203** [comment]
> ld --version

ld --version
GNU ld (GNU Binutils) 2.26.20160125
Copyright (C) 2015 Free Software Foundation, Inc.

**Comment by haruue** [comment]
Please check this bug report in the gnu mail lists:
https://lists.gnu.org/archive/html/bug-binutils/2016-04/msg00221.html

It seems like your LFS installation is a little obsolete. Could you please update it (at least binutils if you don't want to recompile the whole userspace) to a later one?

If you just want to link hysteria against an old version glibc to produce an executable that runs on any environment. Please consider using CentOS 7, so we can get the same environment and inspect this problem much more easier.

**Comment by haruue** [comment]
Since this issue won't occur on an up-to-date Linux distribution. It is no need to update the document of hysteria.

**Comment by bhzhu203** [comment]
Thanks. I updated the LFS to latest  version binutils, the ld issue is solved!

 **But the main issue is "go get/install error"**

go get github.com/HyNetwork/hysteria
go get: github.com/HyNetwork/hysteria@v0.8.6: parsing go.mod:
module declares its path as: github.com/tobyxdd/hysteria
but was required as: github.com/HyNetwork/hysteria

can not go get or install hysteria directly . Seem that you renamed your project before
