### ISSUE TITLE
hysteria什么时候支持手机端使用？

### ISSUE THREAD

**Issue by Sirius2016** [HyNetwork/hysteria#164]
什么时候支持手机端使用？
hysteria加速效果很不错，什么时候支持手机端使用。

**Comment by haruue** [comment]
Hysteria 已经可以在手机上使用。

如果你是 Android 用户， 得益于 SagerNet 项目， 现在可以通过 Hysteria Plugin 来使用 Hysteria 。 你可以访问他们的 [GitHub Release](https://github.com/SagerNet/SagerNet/releases/latest) 下载对应的安装包或者从 [Google Play 商店安装 SagerNet](https://play.google.com/store/apps/details?id=io.nekohasekai.sagernet) 以及 [Hysteria Plugin](https://play.google.com/store/apps/details?id=io.nekohasekai.sagernet.plugin.hysteria) 。

如果你是 iOS 用户， [Shadowrocket](https://apps.apple.com/us/app/shadowrocket/id932747118) 从 2.1.91 版本开始已经支持 Hysteria 。

**Comment by mmm8955405** [comment]
> Hysteria 已经可以在手机上使用。
> 
> 如果你是 Android 用户， 得益于 SagerNet 项目， 现在可以通过 Hysteria Plugin 来使用 Hysteria 。 你可以访问他们的 [GitHub Release](https://github.com/SagerNet/SagerNet/releases/latest) 下载对应的安装包或者从 [Google Play 商店安装 SagerNet](https://play.google.com/store/apps/details?id=io.nekohasekai.sagernet) 以及 [Hysteria Plugin](https://play.google.com/store/apps/details?id=io.nekohasekai.sagernet.plugin.hysteria) 。
> 
> 如果你是 iOS 用户， [Shadowrocket](https://apps.apple.com/us/app/shadowrocket/id932747118) 从 2.1.91 版本开始已经支持 Hysteria 。

是否有教程？ SagerNet 安卓插件和配置的教程

**Comment by flipphos** [comment]
Stash 也有ios版本，支持Hysteria

**Comment by wangyufeng2006** [comment]
电脑上v2ray用hy用的好好的，不知道为啥sagernet连不上，plugin也下载开放权限了，提示”失败:超时“

**Comment by mmm8955405** [comment]
> 电脑上v2ray用hy用的好好的，不知道为啥sagernet连不上，plugin也下载开放权限了，提示”失败:超时“

你是什么人才，才能提出这样的问题

**Comment by wangyufeng2006** [comment]
我的意思是电脑上v2用hy正常，手机上sagernet相同的链接就连不上
