### ISSUE TITLE
Could you add forward feature in server mode?

### ISSUE THREAD

**Issue by quaggalinux** [HyNetwork/hysteria#171]
Could you add forward feature in server mode? Just forward to next socks5 proxy will be enough, because mobile client can't use relay feature.

Thanks,

**Comment by tobyxdd** [comment]
You mean server-side SOCKS5 outbound? It's already scheduled to be in the next release

**Comment by quaggalinux** [comment]
If the server-side SOCKS5 outbound means  forwarding all server traffic to next socks5 proxy then it would be what I meant. Of coruse that scenarios will exclude relay traffic.

**Comment by tobyxdd** [comment]
https://github.com/HyNetwork/hysteria/issues/172
