### ISSUE TITLE
[error:INTERNAL_ERROR: too many gaps in received data] SOCKS5 TCP error

### ISSUE THREAD

**Issue by Mon-ius** [HyNetwork/hysteria#175]
what caused this error? The speed limitation or recv_window_conn and recv_window_client? Maybe add a feature to auto-detect the network and hardware situation when first start the hysteria then save it to .hysteriarc (etc) to auto config.

**Comment by tobyxdd** [comment]
This usually happens when packet loss is too high. Either your connection is really that bad (>50% loss?) or you may have set the bandwidth wildly above the actual available bandwidth.
