### ISSUE TITLE
v0.9.1 *net.UDPConn delivery error

### ISSUE THREAD

**Issue by hfdem** [HyNetwork/hysteria#178]
Enviroment:
- Linux 
- amd64
- hysteria **v0.9.1**

I did `sysctl -w net.core.rmem_max=2500000`, but it still went wrong:

> connection doesn't allow setting of receive buffer size. Not a *net.UDPConn?. See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.

So I tried hysteria **v0.9.0** and it's all good. It seems a bug caused by new quic-go.

**Comment by tobyxdd** [comment]
quic-go wasn't even updated from 0.9.0 to 0.9.1. My guess is you are using faketcp mode, in which it's normal to get this prompt.

**Comment by hfdem** [comment]
> 

Thank you for your reply .

Does the warning affect effecient or anything?

**Comment by tobyxdd** [comment]
No
