### ISSUE TITLE
是否考虑建立 hysteria 分享链接标准？

### ISSUE THREAD

**Issue by Johnshall** [HyNetwork/hysteria#180]
毋庸置疑，设立分享链接标准将提升 hysteria 推行的广度和范围，方便开发者为 hysteria 配套相应的图形化客户端。
建议参考 <https://github.com/XTLS/Xray-core/issues/91>

**Comment by tobyxdd** [comment]
https://github.com/HyNetwork/hysteria#uri-scheme
