### ISSUE TITLE
[feature request] TCP fast open. will it benefit faketcp?

### ISSUE THREAD

**Issue by enihcam** [HyNetwork/hysteria#187]
i know very little about faketcp, but there's a full analysis regarding to TCP fast open: https://blog.apnic.net/2021/07/05/tcp-fast-open-not-so-fast/, so maybe you wanted to check to see if it could help saving few acks here. thx.

**Comment by tobyxdd** [comment]
faketcp is not real TCP so it is irrelevant to real TCP features.
