### ISSUE TITLE
0.9.3 has a glibc compatibality issue in Ubuntu 20.04 

### ISSUE THREAD

**Issue by tefiszx** [HyNetwork/hysteria#192]
OS: ubuntu 20.04 LTS
issue:
./hysteria-linux-amd64-0.9.3 -v
./hysteria-linux-amd64-0.9.3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./hysteria-linux-amd64-0.9.3)

**Comment by fhoshino** [comment]
Same problem on Debian 11

**Comment by enihcam** [comment]
this is not an issue. different glibc libs need different builds. there is no plug-and-play.

or try a rolling-release distro, like arch? :)

**Comment by tobyxdd** [comment]
I guess the version of glibc in the environment used by our GitHub Actions is too new... still trying to figure out what the best solution is.

**Comment by tefiszx** [comment]
The latest release (33901413bf194a1081ed94c6ecd7519e2cf12fa0) resolved glibc compatibality issue in ubuntu 20.04.Thanks @tobyxdd ,thank you for your hard work.

**Comment by tobyxdd** [comment]
But I didn't fix anything... apart from renaming the notun version to `hysteria` and the tun version to `hysteria-tun`

**Comment by tefiszx** [comment]
> But I didn't fix anything... apart from renaming the notun version to `hysteria` and the tun version to `hysteria-tun`

oops!But it does work correctly in ubuntu 20.04LTS.And I noticed that you did an Action workflow for downgrade build  ubuntu to 18.04 for libc compatibility.
