### ISSUE TITLE
[Feature request]Tunnel mode support

### ISSUE THREAD

**Issue by Handsome1080P** [HyNetwork/hysteria#198]
[Feature request]Tunnel mode support,not only portforward.
A_Local--A_Hysteria---B_Hysteria--B_Local

**Comment by tobyxdd** [comment]
Is there any reason a plain old UDP forwarder won't do the job?

**Comment by tobyxdd** [comment]
What do you mean by this "tunnel mode"? Sounds like exactly what the TCP/UDP relay mode can already do

**Comment by Handsome1080P** [comment]
> What do you mean by this "tunnel mode"? Sounds like exactly what the TCP/UDP relay mode can already do

Tunnel the traffic to server local port.Now these settings only can set on client.Like this: Client A ---> Server B ----> Server B local service

**Comment by tobyxdd** [comment]
So set the relay target on the client to `localhost:[whatever port]`?

**Comment by tobyxdd** [comment]
Server's localhost of course...

**Comment by Handsome1080P** [comment]
> Server's localhost of course...

got,thx
