### ISSUE TITLE
看起来很强 OPenwrt也支持了 就等一件脚本了

### ISSUE THREAD

**Issue by mouzi3102** [HyNetwork/hysteria#199]

**Comment by Error996** [comment]
docker不就是一键么。。。。你不会懒到docker都不愿动手吧。。。。

**Comment by mouzi3102** [comment]
> docker不就是一键么。你不会懒到docker。。。都愿意吧。。。。

后来找到了一件脚本呢

**Comment by mouzi3102** [comment]
> docker不就是一键么。你不会懒到docker。。。都愿意吧。。。。

但是不支持一键声称导入链接啊 配置还要手动填写 有的还没办法填
