### ISSUE TITLE
发现hysteria可以和其他TCP服务共用同一个端口

### ISSUE THREAD

**Issue by sdshdv** [HyNetwork/hysteria#212]
VPS上搭建有两项服务，一个是v2ray使用nginx伪装了一个网页，走TCP；一个是hysteria，走UDP。两者都设置了监听443端口，发现并不会互相影响导致端口占用，并且可以同时传输数据

另外这样是不是等于hysteria也有了一个伪装的网页？毕竟域名和端口号都一样

**Comment by tobyxdd** [comment]
你也知道一个是 TCP 一个是 UDP，都不是一种协议谈何伪装
