### ISSUE TITLE
在Windows上后台运行、开机启动、守护进程的规范方式是什么？

### ISSUE THREAD

**Issue by CCCAUCHY** [HyNetwork/hysteria#217]
遇到错误会自动退出程序的特性使我无法制作开机启动脚本，因为刚开机时可能没来得及连上WiFi，且网络中断会导致程序退出，程序意外或手动退出之后可能无法再次启动（bug？）
我尝试过的方法是：
powershell：
`Start-Process "D:\shortcut\hysteria-tun-windows-6.0-amd64.exe" -WindowStyle Hidden`
创建快捷方式：
`D:\shortcut\RunHiddenConsole.exe D:\shortcut\RunHiddenConsole.exe\hysteria-tun-windows-6.0-amd64.exe`

希望官方能开发程序的后台运行模式，或者至少在遇到错误时重试而不是自动退出。

**Comment by tobyxdd** [comment]
https://github.com/HyNetwork/hysteria/pull/219
