### ISSUE TITLE
这个协议是不是挑小鸡啊~为什么我其他协议都OK，换了这个就不通?

### ISSUE THREAD

**Issue by Pacio** [HyNetwork/hysteria#221]
小鸡上部署过vmess,vless,trojan都很正常，不知道为什么这个就不行呢~麻烦帮我看一下配置
![image](https://user-images.githubusercontent.com/6836705/152629667-f2f3731a-2648-4df1-9d20-8de32a49899b.png)
服务器的防火墙都关闭了
客户端ios的小火箭和passwall都试了，都不通
-------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/6836705/152629796-5e3be719-892e-4a4a-bbcb-43217357c456.png)
还有该容器好像没有占用任何端口，是不是问题出在这里？

**Comment by HoshinoNeko** [comment]
![image](https://user-images.githubusercontent.com/21078047/152632875-ec345a55-595c-4da5-a5ff-2e2be427077e.png)
S
**服务端需要一个 TLS 证书。 你可以让 Hysteria 内置的 ACME 尝试自动从 Let's Encrypt 为你的服务器签发一个证书，也可以自己提供。 证书未必一定要是有效、可信的，但在这种情况下客户端需要进行额外的配置。要使用自己的 TLS 证书。**
![image](https://user-images.githubusercontent.com/21078047/152632875-ec345a55-595c-4da5-a5ff-2e2be427077e.png)
参考快速入门 [https://github.com/HyNetwork/hysteria/wiki/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8](https://github.com/HyNetwork/hysteria/wiki/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8)
**服务端需要一个 TLS 证书。 你可以让 Hysteria 内置的 ACME 尝试自动从 Let's Encrypt 为你的服务器签发一个证书，也可以自己提供。 证书未必一定要是有效、可信的，但在这种情况下客户端需要进行额外的配置。要使用自己的 TLS 证书。**

**Comment by Pacio** [comment]
> 

有证书啊，我自己申请好的，就放在那个路径下面啊

**Comment by Pacio** [comment]
> ![image](https://user-images.githubusercontent.com/21078047/152632875-ec345a55-595c-4da5-a5ff-2e2be427077e.png)
> 
> **服务端需要一个 TLS 证书。 你可以让 Hysteria 内置的 ACME 尝试自动从 Let's Encrypt 为你的服务器签发一个证书，也可以自己提供。 证书未必一定要是有效、可信的，但在这种情况下客户端需要进行额外的配置。要使用自己的 TLS 证书。** 参考快速入门 https://github.com/HyNetwork/hysteria/wiki/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8

有证书啊，我自己申请好的，就放在那个路径下面啊

**Comment by HoshinoNeko** [comment]
检查目录是否在容器内完成映射
启动容器后执行 `docker logs hysteria` 查看日志中的报错
