### ISSUE TITLE
WIKI是否有误

### ISSUE THREAD

**Issue by zzlinwq** [HyNetwork/hysteria#229]
自定义 CA 方法
假设服务器地址是 123.123.123.123, 端口5678UDP/TCP协议未被防火墙拦截
已经安装了 openssl
hysteria 已经安装在 /root/hysteria/目录下
4. 生成自定义CA证书
服务端：复制 server.json、 hysteria.server.crt、 hysteria.server.key 到 /root/hysteria/ 目录下，运行 /root/hysteria/hysteria -c /root/hysteria/server.json server 命令

客户端：假设客户端运行目录也为/root/hysteria, 复制 client.json、hysteria.ca.crt 到 /root/hysteria/ 目录下，运行 /root/hysteria/hysteria -c /root/hysteria/client.json 命令

生成CA证书之后，根据自身情况修改服务器地址、端口和证书文件路径，加上obfs和alpn是防止首次在某些环境下被墙，第一次在全参数情况下测试通过后，可以自身网络环境删除不必须要参数，比如obfs和alpn.

iOS 端如果使用的是小火箭 Shadowrocket，可以把文件hysteria.ca.crt airdrop到手机，然后在手机上安装并信任后, 就可以使用自定义CA证书了。

“可以把文件hysteria.ca.crt airdrop到手机”这一句是否有误？应该是hysteria.server.crt？
不然hysteria.ca.crt这个文件怎么得来？
我是苹果手机，用小火箭 Shadowrocket  死活不行

**Comment by tobyxdd** [comment]
就是 `hysteria.ca.crt`。如果你是完整按照说明做的话，第四步会得到这个文件的。
