### ISSUE TITLE
Failed tu run the client when missing `up_mbps` or `down_mbps` in the config

### ISSUE THREAD

**Issue by hronro** [HyNetwork/hysteria#233]
Got this error when I try to run the client:

```log
2022-02-18T14:53:28+08:00 [FATA] [file:/usr/local/etc/hysteria/config.json] [error:invalid speed] Failed to parse client configuration
```

https://github.com/HyNetwork/hysteria/blob/9b78d1cad7ee4946e33b9f2ba93256fa822ab368/cmd/config.go#L204

Probably it should be `if c.UpMbps < 0 || c.DownMbps < 0`?

**Comment by haruue** [comment]
https://github.com/HyNetwork/hysteria/wiki/Quick-Start#client
> `up_mbps` and `down_mbps` are **mandatory** on the client side. Try to fill in these values as accurately as possible according to your network conditions, as they are crucial for Hysteria to work optimally.
