### ISSUE TITLE
[Feature] add hysteria as Shadowsocks-NET / Qv2ray Plugin

### ISSUE THREAD

**Issue by egg1234** [HyNetwork/hysteria#237]
Do you have plans to add hysteria as Shadowsocks-NET / Qv2ray Plugin?

This project is the brand new Qv2ray v3.0.0 .
https://github.com/Shadowsocks-NET/Qv2ray

Thanks,

**Comment by mmm8955405** [comment]
不一样的项目， 为什么要提这种需求

**Comment by egg1234** [comment]
现在已经解决了，https://github.com/MatsuriDayo/nekoray 项目已经做到了标题希望的功能(issue #403)，不需要在Shadowsocks-NET / Qv2ray项目里面做了

**Comment by trulyliu** [comment]
https://github.com/trulyliu/QvPlugin-Hysteria
Qv2ray的plugin， 目前actions有问题。我没有mac和win环境。
