### ISSUE TITLE
Freebsd Version Run Error

### ISSUE THREAD

**Issue by Error996** [HyNetwork/hysteria#253]
go buid command:

`CGO_ENABLED=0 GOOS=freebsd go build -o hysteria ./cmd`

Error code:

`[ERRO] [error:Application error 0x1: protocol error] Failed to initialize client`

[hysteria.zip](https://github.com/HyNetwork/hysteria/files/8174995/hysteria.zip)

**Comment by Error996** [comment]
last work good version : 0.9.7

**Comment by haruue** [comment]
Cannot reproduce this bug on my FreeBSD test environment `FreeBSD 13.0-RELEASE amd64`, with hysteria tag `v1.0.1`.

Could you please provide your client config (remove all server & auth info) and tell us the FreeBSD version you are using?

**Comment by Error996** [comment]
```
{
  "server": "google.com:36711",
  "obfs": "fuck me till the daylight",
  "up_mbps": 1000,
  "down_mbps": 1000,
  "socks5": {
    "listen": "127.0.0.1:50001"
  },
  "ca": "/root/my.ca",
  "recv_window_conn": 52428800,
  "recv_window": 209715200
}
```

> FreeBSD 12.2-STABLE (pfsense)

```
# go version
go version go1.17.5 linux/amd64
```

**Comment by Error996** [comment]
```
CGO_ENABLED=0 GOOS=freebsd go build ./cmd
```

**Comment by haruue** [comment]
Oh I see

> [ERRO] [error:Application error 0x1: protocol error] Failed to initialize client

The "protocol error" means you are using a hysteria server that older than your client. Please update & restart hysteria on your server.
