### ISSUE TITLE
[feature request] UDP PacketAddr (aka full-cone NAT)

### ISSUE THREAD

**Issue by enihcam** [HyNetwork/hysteria#255]
i don't know if hysteria shall cover this scenario or not, but full-cone NAT is support important for low-latency gaming, just like those supported by v2ray, ss, trojan, etc, unless it is by-design unneeded.

**Comment by tobyxdd** [comment]
As far as I know, hysteria's UDP is already full-cone (except in TProxy mode which is symmetric). What mode are you talking about?

**Comment by enihcam** [comment]
> As far as I know, hysteria's UDP is already full-cone (except in TProxy mode which is symmetric). What mode are you talking about?

alright, I didn't know about this. yes, I'm using hysteria via tproxy right now. it'd be good if this could be documented somewhere. thx.

**Comment by enihcam** [comment]
@tobyxdd
a general question: between tun and tproxy which mode would you recommend? thanks.
I'm not familiar with the tun mode, do you have a suggested iptables config? thanks again.

**Comment by tobyxdd** [comment]
currently tproxy mode should have much better performance, so I'd recommend this over tun
