### ISSUE TITLE
[feature request] reverse tunnel via hysteria

### ISSUE THREAD

**Issue by enihcam** [HyNetwork/hysteria#262]
i'm looking for an approach that helps expose a local client listening port at server side (via hysteria), e.g.

[INTRANET IP]:443(listening) <---hysteria--- [PUBLIC IP]:443(listening)

Concretely, my router is running a bittorrent client announcing its DHT port to a tracker, unfortunately what the tracker see is the IP of the hysteria server (public). I need somehow to establish a 'reverse tunnel' that can forward the listened packets (both UDP and TCP) back to intranet.

Do you have any suggestions? Thanks.

**Comment by xtccc** [comment]
see the frp

**Comment by enihcam** [comment]
> see the frp

yes but then it would be like hysteria(frp(traffic)), i.e. unnecessary nesting.

**Comment by xtccc** [comment]
why you need the hysteria?
you can use the frp only

**Comment by enihcam** [comment]
> 
frp traffic can be easily identified and 'QoS'ed.

**Comment by tobyxdd** [comment]
Dup of https://github.com/HyNetwork/hysteria/issues/55
