### ISSUE TITLE
[功能请求] 能否为Windows平台编译能够后台运行的.exe文件

### ISSUE THREAD

**Issue by CCCAUCHY** [HyNetwork/hysteria#264]
https://github.com/XTLS/Xray-core/pull/861 可以参考隔壁xray的实现方式

**Comment by chika0801** [comment]
start /min "Hysteria Service" cmd /c "hysteria.exe" --log-level info

建一个bat 放开始菜单来自启动。

调试也方便。你无前台EXE每次关还要在任务管理器找到来结束进行。
