### ISSUE TITLE
同時运行多个服务器?

### ISSUE THREAD

**Issue by delphinuz** [HyNetwork/hysteria#268]
标题写的不好，主要意思是，能否像v2ray一样，一个.json里可以放多个服务器？如下：

{server:"SERVER A",......, socks:{listen:localhost:8080}},
{server:"SERVER B",......, socks:{listen:localhost:8082}},
{server:"SERVER C",......, socks:{listen:localhost:8084}},
{server:"SERVER D",......, socks:{listen:localhost:8086}}

这样会只要运行一个hy，就可以依不同的localhost:port，将数据传到对应的server。

目前的方式需要运行4个hy。

**Comment by tobyxdd** [comment]
从资源占用的角度来说，程序层面支持多个 server 和你单独运行 4 个进程并没什么区别，而且还不好单独控制开关了。因此这个 feature 没有计划添加。
