### ISSUE TITLE
为啥YouTube的视频看不了？

### ISSUE THREAD

**Issue by wander555** [HyNetwork/hysteria#270]
如题，搭建成功，youtube可以登录，点击视频直接loading黑屏
用的是默认的配置，acme自动申请证书模式，客户端是用的passwall，求教

**Comment by wander555** [comment]
补充一点，google.com也访问不了，真心求教

**Comment by giodano0718** [comment]
我也一样有这个问题，楼上兄弟解决了吗？怎么解决的？

**Comment by QIN2DIM** [comment]
![168412964-a1e4bb50-4222-4780-8e37-64af2552975d](https://user-images.githubusercontent.com/62018067/168515932-62cb87b7-e28b-4898-abf1-3b1217c6a8db.jpg)
