### ISSUE TITLE
校验和、多证书及更新检查

### ISSUE THREAD

**Issue by fjn308** [HyNetwork/hysteria#272]
感谢作者的工作，第一次使用 Hesteria，有两个问题想问一下：
1，在客户端（Windows）我希望用一个脚本来根据 latest release 更新，其中有一步是检查下载的正确性，请问有办法找到 releases 中二进制文件的检验和吗（比如通过 GitHub API 之类的）？
2，在服务端，请问是否可以配置对应不同域名的多个证书文件？（似乎 ACME 可以配置多个域名，但无法直接提供多个现成的证书？）

**Comment by tobyxdd** [comment]
1. 我可以在之后的 release 每个 binary 对应带一个 sha256 文件用来校验。确实见到过不少项目这样
2. 目前没有这个 feature，我看下好不好加吧

**Comment by fjn308** [comment]
明白了！非常感谢您的回复！

**Comment by fjn308** [comment]
刚刚注意到 Windows 端有一个 flag 是 --no-check，但描述不多，所以想顺便问一下：在有新版本时，Hysteria 会做出某种更新行为吗？还是会在日志中提示有新的版本？

**Comment by haruue** [comment]
> 刚刚注意到 Windows 端有一个 flag 是 --no-check，但描述不多，所以想顺便问一下：在有新版本时，Hysteria 会做出某种更新行为吗？还是会在日志中提示有新的版本？

在有新版本时，Hysteria 只会在日志中提示有新的版本， 当前不会有任何更新自身的行为。

https://github.com/HyNetwork/hysteria/blob/9c7a06bc794f1286b83f975c1a1f03bd927ba342/cmd/update.go#L21-L29

**Comment by fjn308** [comment]
> > 刚刚注意到 Windows 端有一个 flag 是 --no-check，但描述不多，所以想顺便问一下：在有新版本时，Hysteria 会做出某种更新行为吗？还是会在日志中提示有新的版本？
> 
> 
> 
> 在有新版本时，Hysteria 只会在日志中提示有新的版本， 当前不会有任何更新自身的行为。
> 
> 
> 
> https://github.com/HyNetwork/hysteria/blob/9c7a06bc794f1286b83f975c1a1f03bd927ba342/cmd/update.go#L21-L29

明白！感谢回复！

**Comment by jantacy** [comment]
能否考虑下多证书文件支持呢？感谢 @tobyxdd
