### ISSUE TITLE
关于hy服务端socks5_outbound会把域名解析成ip再输出的问题

### ISSUE THREAD

**Issue by yanbook** [HyNetwork/hysteria#273]
你好，我不大懂技术，描述的可能不专业，请见谅

1 我的用法是在服务器端，使用socks5_outbound 把流量转发到xray/v2ray,以方便使用它的分流等功能（我比较喜欢也稍微熟悉一点xray的分流）

2 在使用过程中发现，hy会把域名解析成ip后再socks5_outbound转发出去，于是我在xray的inbound中开启sniffing模块，大部分时候都是成功的，可是有一两成的概率还是无法完全恢复对应的域名和ip，导致分流失败。

3 所以，想请问作者能否在socks5_outbound转发的时候，不要把域名解析成ip？

**Comment by yanbook** [comment]
在telegram讨论中得知是因为我分流的google域名，google使用的是quic，而xray无法sniffing quic，这才导致无法分流。

还是想请教一下，能否将socks5_outbound修改成不解析ip，这样可以一劳永逸解决问题呢，谢谢

**Comment by fefz** [comment]
v2ray 是不是可以sniffing quic
