### ISSUE TITLE
incoming hysteria traffic (UDP packets) dropped with `ctstate=INVALID`, but meanwhile its connection `[ASSURED]` in conntrack list

### ISSUE THREAD

**Issue by enihcam** [HyNetwork/hysteria#277]
The hysteria traffic slows down in few seconds after a new reboot, then I see a huge amount of incoming reply packets dropped at `mangle PREROUTING` stage:

```
pkts bytes target        prot opt in     out     source               destination
327K  489M LOG_AND_DROP  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
```

and in `dmesg`:

```
IN=ppp0 OUT= MAC= SRC=52.220.151.177 DST=10.17.175.251 LEN=1496 TOS=0x00 PREC=0x00 TTL=49 ID=0 PROTO=UDP SPT=4444 DPT=28317 LEN=1476
```
> only for example, `52.220.151.177` is the VPS IP and `10.17.175.251` is my gateway IP.

but in `conntrack` list, I found the UDP connection is already `ASSURED`:

```
udp      17 118 src=10.17.175.251 dst=52.220.151.177 sport=28317 dport=4444 src=52.220.151.177 dst=10.17.175.251 sport=4444 dport=28317 [ASSURED] mark=0 use=1
```

here is my `iptables` config:

```
*nat
:PREROUTING ACCEPT [-:-]
:INPUT ACCEPT [-:-]
:OUTPUT ACCEPT [-:-]
:POSTROUTING ACCEPT [-:-]
-A POSTROUTING -s 192.168.0.0/24 -o ppp0 -j MASQUERADE
COMMIT

*filter
:INPUT DROP [-:-]
:FORWARD DROP [-:-]
:OUTPUT ACCEPT [-:-]
-A INPUT -i ppp0 -j -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i br0 -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A FORWARD -i ppp0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i br0 -j ACCEPT
COMMIT

*mangle
:PREROUTING ACCEPT [-:-]
:INPUT ACCEPT [-:-]
:FORWARD ACCEPT [-:-]
:OUTPUT ACCEPT [-:-]
:POSTROUTING ACCEPT [-:-]
:TPROXY_MARK - [-:-]
:OUTPUT_MARK - [-:-]
:LOG_AND_DROP - [-:-]
-A LOG_AND_DROP -j LOG --log-level 7 --log-tcp-sequence --log-tcp-options --log-ip-options --log-uid
-A LOG_AND_DROP -j DROP


-A PREROUTING -i ppp0 -m conntrack --ctstate INVALID -j LOG_AND_DROP         <---------HUGE AMOUNT OF HITS


-A PREROUTING ! -i ppp0 -j TPROXY_MARK
-A FORWARD -o ppp0 -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
-A OUTPUT -o ppp0 ! -p icmp -j OUTPUT_MARK
-A TPROXY_MARK -m set --match-set whitelist dst -j RETURN
-A TPROXY_MARK -p udp -j TPROXY --on-port 1080 --on-ip 127.0.0.1 --tproxy-mark 0x1/0xffffffff
-A TPROXY_MARK -p tcp -j TPROXY --on-port 1080 --on-ip 127.0.0.1 --tproxy-mark 0x1/0xffffffff
-A OUTPUT_MARK -m set --match-set whitelist dst -j RETURN
-A OUTPUT_MARK -j MARK --set-xmark 0x1/0xffffffff
COMMIT
```

any ideas?

**Comment by haruue** [comment]
It is always OK to use `-m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT` to accept traffic of all opened connections. But I don't think `--ctstate INVALID -j LOG_AND_DROP` is a good practice. Since UDP itself is a stateless protocol, why do you think conntrack would be able to track it state effectively?

**Comment by enihcam** [comment]
> It is always OK to use `-m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT` to accept traffic of all opened connections. But I don't think `--ctstate INVALID -j LOG_AND_DROP` is a good practice. Since UDP itself is a stateless protocol, why do you think conntrack would be able to track its state effectively?

According to kernel logic, conntrack table records UDP connections with pseudo-state `UNREPLIED` and `ASSURED`, this is also documented at https://www.frozentux.net/iptables-tutorial/chunkyhtml/x1555.html.

Diving into the `conntrack` code, it's easy to find the call path of checking UDP is invalid or not:
- the final result is returned by validating `nf_ct_get(skb, &ctinfo)` is zero (L170-L177). https://github.com/torvalds/linux/blob/v5.10/net/netfilter/xt_conntrack.c#L177 ->
https://github.com/torvalds/linux/blob/v5.10/include/net/netfilter/nf_conntrack.h#L152 ->
https://github.com/torvalds/linux/blob/v5.10/include/linux/skbuff.h#L4127
- here you can see the final result is `INVALID` if `skb->_nfct` is zero, which is caused by `nf_conntrack_handle_packet()` returning -1 (`-NF_ACCEPT`).
https://github.com/torvalds/linux/blob/v5.10/net/netfilter/nf_conntrack_core.c#L1852
https://github.com/torvalds/linux/blob/v5.10/net/netfilter/nf_conntrack_core.c#L1758
https://github.com/torvalds/linux/blob/v5.10/net/netfilter/nf_conntrack_proto_udp.c#L94
- and everything end up in `udp_error()`  explaining when a UDP 'connection' will be considered as invalid by 'health state' of one of its packets. 
https://github.com/torvalds/linux/blob/v5.10/net/netfilter/nf_conntrack_proto_udp.c#L45

```c
static bool udp_error(struct sk_buff *skb,
		      unsigned int dataoff,
		      const struct nf_hook_state *state)
{
	unsigned int udplen = skb->len - dataoff;
	const struct udphdr *hdr;
	struct udphdr _hdr;

	/* Header is too small? */
	hdr = skb_header_pointer(skb, dataoff, sizeof(_hdr), &_hdr);
	if (!hdr) {
		udp_error_log(skb, state, "short packet");
		return true;
	}

	/* Truncated/malformed packets */
	if (ntohs(hdr->len) > udplen || ntohs(hdr->len) < sizeof(*hdr)) {
		udp_error_log(skb, state, "truncated/malformed packet");
		return true;
	}

	/* Packet with no checksum */
	if (!hdr->check)
		return false;

	/* Checksum invalid? Ignore.
	 * We skip checking packets on the outgoing path
	 * because the checksum is assumed to be correct.
	 * FIXME: Source route IP option packets --RR */
	if (state->hook == NF_INET_PRE_ROUTING &&
	    state->net->ct.sysctl_checksum &&
	    nf_checksum(skb, state->hook, dataoff, IPPROTO_UDP, state->pf)) {
		udp_error_log(skb, state, "bad checksum");
		return true;
	}

	return false;
}
```

In a conclusion, hysteria traffic in UDP packets will be dropped if either of the two conditions occurs:
1. Header is too small
2. Truncated/malformed packets

> Why not `Checksum invalid?` it's because I reproduced this issue even when I turned off NF checksum, i.e. `net.netfilter.nf_conntrack_checksum = 0`.

cc @tobyxdd

**Comment by tobyxdd** [comment]
So according to your conclusion, this is caused by malformed UDP packets? I don't think hysteria itself has anything to do with this if so, as it uses standard UDP sockets for sending & receiving packets. It's not even possible to send such malformed packets with a layer 4 API.

**Comment by enihcam** [comment]
> So according to your conclusion, this is caused by malformed UDP packets? I don't think hysteria itself has anything to do with this if so, as it uses standard UDP sockets for sending & receiving packets. It's not even possible to send such malformed packets with a layer 4 API.

I see. thx for the details. does it mean that even if i were to change hysteria client from tproxy mode to tun mode, this issue would be still existing because everything of hysteria is built on top of L4?
