### ISSUE TITLE
能否支持ipv6协议

### ISSUE THREAD

**Issue by gitrepo** [HyNetwork/hysteria#283]
试了一下好像不支持ipv6协议。

**Comment by xtccc** [comment]
支持ipv6 
你把服务端客户端配置打码发出来
发下客户端日志

**Comment by brick2008** [comment]
我在多个ipv6 only的机器上都正常使用

**Comment by gitrepo** [comment]
服务端没问题
客户端提示
 [error:address 2604:5040:11:4e0::37b9:4443: too many colons in address] Failed to initialize client

**Comment by brick2008** [comment]
ipv6地址要加方括号  [ ]

**Comment by gitrepo** [comment]
恩，ipv6地址处理好了，现在配置也能加载
现在出现下面错误
[ERRO] [error:timeout: no recent network activity] Failed to initialize client

**Comment by gitrepo** [comment]
不然我服务器再开个给ipv6的配置，用另外一个端口试一下。

**Comment by gitrepo** [comment]
服务器配置
 {
  "listen": ":4443",
  "cert": "/etc/letsencrypt/live/www.suifeng.gq/fullchain.pem",
  "key": "/etc/letsencrypt/live/www.suifeng.gq/privkey.pem",
  "obfs": "*****",
  "recv_window_conn": 65536000,
  "recv_window_client": 262144000,
  "max_conn_client": 4096,
  "up_mbps": 1000,
  "down_mbps": 1000
}
客户端配置
{
  "server": "[2604:5040:11:4e0::37b9]:4443",
  "obfs": "*****",
  "up_mbps": 1000,
  "down_mbps": 1000,
  "recv_window_conn": 65536000,
  "recv_window": 262144000,
  "socks5": {
    "listen": "127.0.0.1:1081"
  },
  "http": {
    "listen": "127.0.0.1:8081"
  }
}

**Comment by xtccc** [comment]
客户端要写 server name
"server_name": "real.name.com",

**Comment by gitrepo** [comment]
> 客户端要写 server name "server_name": "real.name.com",

写了，还是[ERRO] [error:timeout: no recent network activity] Failed to initialize client
{
  "server": "v6.suifeng.gq:9443",
  "obfs": "",
  "up_mbps": 1000,
  "down_mbps": 1000,
  "recv_window_conn": 65536000,
  "recv_window": 262144000,
  "socks5": {
    "listen": "127.0.0.1:1081"
  },
  "http": {
    "listen": "127.0.0.1:8081"
  }
}
服务端配置
{
  "listen": ":9443",
  "cert": "/etc/letsencrypt/live/v6.suifeng.gq/fullchain.pem",
  "key": "/etc/letsencrypt/live/v6.suifeng.gq/privkey.pem",
  "obfs": "",
  "recv_window_conn": 65536000,
  "max_conn_client": 4096,
  "up_mbps": 1000,
  "down_mbps": 1000
}

**Comment by xtccc** [comment]
那也许是服务商阻断了udp ， 用作者的方法排除下吧
```
注意能使用 curl 正常请求服务器域名并不能证明能够正常进行 UDP 通信， 可以按照这里的方法进行排查。
停止服务器上的 Hysteria 服务端。
在客户端和服务端安装 socat。
在服务端一侧执行命令 socat - UDP6-LISTEN:36712,reuseaddr,fork， 你需要把命令中的端口号换成你为 Hysteria 服务端设置的端口号。
在客户端一侧执行命令 socat - UDP:example.com:36712， 你需要把命令中的服务器和端口号换成 Hysteria 客户端配置中的 server 项内容。
如果两边的 socat 都能正常启动， 你可以尝试在两侧输入任意内容并按下回车， 如果你输入的内容出现在了另一侧， 则客户端和服务端的 UDP 能正确连通。 如果做不到这一点， 说明客户端到服务端的 UDP 连接可能被阻断。
```

**Comment by gitrepo** [comment]
@xtccc 
测试了9443端口的udp通信正常。

**Comment by xtccc** [comment]
> @xtccc 
> 测试了9443端口的udp通信正常。
你把 downmbps和upmbps都调小点试试吧，
或者是别的参数的问题，你最好把多余的参数都去了试试

**Comment by togls** [comment]
服务端配置

"listen": "[::]:9443"

**Comment by gitrepo** [comment]
没用，留最基本的参数还是同样问题

> 服务端配置
> 
> "listen": "[::]:9443"

一样的，还是[ERRO] [error:timeout: no recent network activity] Failed to initialize client

**Comment by xtccc** [comment]
你测试的时候 obfs去掉试试

**Comment by gitrepo** [comment]
> 你测试的时候 obfs去掉试试

@xtccc 
obfs去掉正常，why!

**Comment by xtccc** [comment]
你把obfs 里写点内容试试？ 
我怀疑是作者没考虑obfs 为空字符串的情况

**Comment by gitrepo** [comment]
> 你把obfs 里写点内容试试？ 我怀疑是作者没考虑obfs 为空字符串的情况

有内容的，我贴上来去掉了。

**Comment by xtccc** [comment]
那就只能是你服务端 客户端 obfs 不一样 ，导致的 error:timeout: no recent network activity

**Comment by gitrepo** [comment]
> 那就只能是你服务端 客户端 obfs 不一样 ，导致的 error:timeout: no recent network activity

不会的，我还试了改一个其它的。
然后我在ipv4地址上的配置完全正常，配置一样。

**Comment by xtccc** [comment]
那我只有最后一种猜想了 
你客户端服务端版本一致吗？
如果也一致那等作者或其他人吧 我想不出原因了

**Comment by gitrepo** [comment]
> 那我只有最后一种猜想了 你客户端服务端版本一致吗？ 如果也一致那等作者或其他人吧 我想不出原因了

哈哈，当然一致了，不过是1.01的，我升级到最新的试一下。

**Comment by gitrepo** [comment]
经测试1.02版本也是同样问题，看来不能启用obfs.

**Comment by NinjaUmbra** [comment]
使用hy最新的版本 测试 obfs 正常使用 请你自己去排除
  "protocol": "udp",
  "obfs": "xxxxx",
确保server字段正确 客户端建议ip:port
如果是ipv6
需要
  "server": "[ipv6]:port",
另外 你服务端配置的 protocol去哪了

**Comment by NinjaUmbra** [comment]
https://github.com/HyNetwork/hysteria/issues/283#issuecomment-1091505779

**Comment by NinjaUmbra** [comment]
还有 请你填写真实本地宽带网络真实的带宽峰值

**Comment by windias** [comment]
和你同样问题，开obfs就no recent network activity。请问最后解决了吗？
和protocol配置无关。
