### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by wander555** [HyNetwork/hysteria#285]
client side works on debian10 , and always failed because of this `too many open files`
 serverside works fine even the  client side ailed 
what's the reason ?

**Comment by haruue** [comment]
The max fd count a process may open is default limited to 1024 on the Linux but can be increased like `sysctl fs.file-max=8192`.
Maybe you should check the output of `sysctl fs.file-max`.

And could you please post your client config here? So we will be able to reproduce this issue on the Debian 10.

**Comment by wander555** [comment]
> 
I checked my client config,just as simple as the wiki suggested...
I guess maybe is the socket port is 1080,and the port is quite popular in debian10,maybe other thread used it too...
I try to change the port and see if it works fine...

plus,`fs.file-max = 92233720368` this is the file-max on my linux,so I don't think is this reason...

**Comment by Roll8ack** [comment]
Maybe your proxy has too much requests. You could use `ulimit -n` to check open files limitation, if it limits to 1024, you can try to increase it. E.g.  `ulimit -n 8192`
