### ISSUE TITLE
甲骨文4C ARM CPU满负载在50% 请问如何跑满4核以提高带宽

### ISSUE THREAD

**Issue by lazzman** [HyNetwork/hysteria#292]
![image](https://user-images.githubusercontent.com/20707207/163716011-cb3d87af-d303-4c4d-a446-2ff1c6a62a7e.png)
![image](https://user-images.githubusercontent.com/20707207/163716023-ebc245dc-438b-4520-88c5-a218f84774ac.png)

**Comment by lazzman** [comment]
![image](https://user-images.githubusercontent.com/20707207/163716065-00353277-85a3-49af-adcf-55f128263612.png)
![image](https://user-images.githubusercontent.com/20707207/163716072-3715ebb2-c98f-4380-9ae4-e15efe160764.png)

多次测试 CPU负载均为50%以内

客户端应该不是瓶颈
![image](https://user-images.githubusercontent.com/20707207/163716111-aed3b47d-8c70-4a01-9307-cff0f3770918.png)

**Comment by BrightVan** [comment]
你这个甲骨文的面板是啥？

**Comment by lazzman** [comment]
> 

[哪吒监控](https://github.com/naiba/nezha)
