### ISSUE TITLE
resolver DNS查询支持DoT/DoH

### ISSUE THREAD

**Issue by Tsukimeizi** [HyNetwork/hysteria#299]
希望能加入这个功能
例如：
DoT: tls://1.1.1.1:853
DoH: https://1.1.1.1/dns-query

参考：https://latest.gost.run/concepts/resolver/

**Comment by viagram** [comment]
> 希望能加入这个功能 例如： DoT: tls://1.1.1.1:853 DoH: https://1.1.1.1/dns-query
> 
> 参考：https://latest.gost.run/concepts/resolver/

我意思是hysteria能支持DoT,DoH,等dns查询方式，配置文件中
`"resolver": "1.1.1.1:53",`
能够支持类似以下的dns配置和查询方式
`"resolver": "udp://1.1.1.1:53",`
`"resolver": "tls://1.1.1.1:53",`
`"resolver": "tcp://1.1.1.1:53",`
`"resolver": "https://1.1.1.1:53",`
