### ISSUE TITLE
Switch to a better tun2socks implementation for tun mode

### ISSUE THREAD

**Issue by tobyxdd** [HyNetwork/hysteria#306]
https://github.com/xjasonlyu/tun2socks

**Comment by hellodword** [comment]
Any dev branch about this?

**Comment by f4nff** [comment]
[https://github.com/xjasonlyu/tun2socks](https://github.com/xjasonlyu/tun2socks)

这个库明显比 https://github.com/eycorsican/go-tun2socks 好太多，
go-tun2socks 根本跑不上速度，最多100M


https://github.com/xjasonlyu/tun2socks 设计理念很好，不干涉dns 路由命令，因为平台不同，执行的路由命令都不同，
还不如交给脚本去实现。

**Comment by sy1989** [comment]
wireguard-go里面tun不错，多平台

**Comment by f4nff** [comment]
@sy1989   +1

**Comment by haruue** [comment]
> @sy1989: wireguard-go里面tun不错，多平台

tun 是用来处理 L3 （网络层）数据包的， 而 WireGuard 本身也是一个提供 L3 服务的 VPN， 因此 WireGuard 的 tun 只需要做好适配各个平台上创建 tun 接口以及纯 L3 数据包转发的操作。

然而 tun2socks 要解决的问题远不仅仅是创建 tun ， 重中之重是如何 2socks 。

但是要把处理 L3 数据包的 tun， 串联到一个提供 L4 （传输层）转发的代理上（也就是 2socks）。 这种情况下需要解析每一个 IP 数据包并「翻译」成 L4 上的操作。 UDP 还好， 充其量也就一个分片和 checksum 的问题。 但是 TCP 就麻烦了， 这种情况下需要维护 TCP 状态， 需要处理 TCP 栈可能发生的任何情况（创建连接、 关闭连接、 重传、 超时）， tun2socks 都得「扮演」真的 TCP 服务端来生成这些 IP 数据包， 然后通过 tun 接口发出去。  此外， 如果远程服务器报错（比如客户端访问了一个不可达的地址或者服务端端口没有开）， tun2socks 还需要作为路由器生成并返回对应的 ICMP 或者 TCP RST。 这整个 2socks 的过程， 远远比创建 tun 复杂得多， 也是 [xjasonlyu/tun2socks](https://github.com/xjasonlyu/tun2socks) 这个项目借助 [gVisor](https://github.com/google/gvisor) 所实现的。

**Comment by f4nff** [comment]
换   https://github.com/xjasonlyu/tun2socks
起嘛纯go，交叉编译方便太多了。

**Comment by haruue** [comment]
> @f4nff: 换 https://github.com/xjasonlyu/tun2socks 起嘛纯go，交叉编译方便太多了。

我们也一直想换到 [xjasonlyu/tun2socks](https://github.com/xjasonlyu/tun2socks) ， 但是遇到了一些问题。

第一是 [xjasonlyu/tun2socks](https://github.com/xjasonlyu/tun2socks) 并不是一个库， 它是个 executable ， 它并没有很明确的公开接口可以直接拿来调用。 

因此换到这个实现最好的办法是我们自己把它改成一个可以直接拿来用的库， 但是 [xjasonlyu/tun2socks](https://github.com/xjasonlyu/tun2socks) 使用的开源协议和 Hysteria 的不兼容， 要完全重新写是比较浪费时间的， 考虑到用户总是可以直接使用这个项目来转发 Hysteria 提供的 socks5 代理， 换到这个实现其实并不会增强多少用户体验， 这个计划就暂时被搁置了。
