### ISSUE TITLE
添加path字段

### ISSUE THREAD

**Issue by inaryart** [HyNetwork/hysteria#315]
我想在一个vps使用v2ray以及hysteria，我想通过以下形式搭建服务
- 域名/v2ray_path
- 域名/hysteria_path

**Comment by haruue** [comment]
hysteria 使用 UDP ， 它不会和你服务器上监听相同 TCP 端口的 v2ray 或者反代服务器（如 nginx 或者 caddy）冲突， 你也不可以使用这样的反代服务器来反代 hysteria 。
