### ISSUE TITLE
Can anyone make some explaination on GFW identification

### ISSUE THREAD

**Issue by moonpole** [HyNetwork/hysteria#316]
Connection speed is one of the key factors we care. Another key factor is safety. From your point of view, does GFW have the ability to analyse the data usage or packet structure to identify its proxy behavior?

**Comment by tobyxdd** [comment]
> does GFW have the ability to analyse the data usage or packet structure to identify its proxy behavior?

It doesn't, for now, obviously. Otherwise it would be unusable for users in China already.

But you are more than welcome to look into potential detection methods for the current protocol, and I will try my best to fix them.
