### ISSUE TITLE
Huge problems at higher speed

### ISSUE THREAD

**Issue by PtDragon** [HyNetwork/hysteria#32]
Hello!
I did test this program and found that it does not work for gigabit speeds
I constantly get errors like
error="INTERNAL_ERROR: too many gaps in received data"
and speed gets capped around 240-250mbit (i have 10Gbit on server and 2x1Gbit(redundant) on client).

**Comment by tobyxdd** [comment]
could be an issue with some of the QUIC default parameters I think, I'll try to reproduce and fix. Thanks for the feedback

**Comment by tobyxdd** [comment]
Hi there, it's been quite a while. I've updated the code a lot since, and quic-go itself has gone through many updates. Are you interested in giving it a try again?
