### ISSUE TITLE
真的好牛呀

### ISSUE THREAD

**Issue by ymmshi** [HyNetwork/hysteria#321]
virmach 起飞了，2000直接飙到90000，有个问题请教一下，请问是否可以实现指定域名走ipv4或ipv6呢，想让google走ipv6，其它走ipv4，不然总有异常流量提醒。另外，请问如何捐赠呢，好的项目就得支持一下。

**Comment by chika0801** [comment]
建议你更换更好的VPS，最好是CN回程优化的。线路太垃，什么都救不了2333

**Comment by ymmshi** [comment]
> 建议你更换更好的VPS，最好是CN回程优化的。线路太垃，什么都救不了2333

我已经满足了😂
