### ISSUE TITLE
转发怎样用，能支持vless或者vmess进——hysteria客户端——hysteria服务端——vless或者vmess出吗

### ISSUE THREAD

**Issue by jfplyl999** [HyNetwork/hysteria#324]
转发怎样用，能支持vless或者vmess进——hysteria客户端——hysteria服务端——vless或者vmess出吗

**Comment by haruue** [comment]
v2fly 支持 socks5 作为 inbounds 和 outbounds
https://www.v2fly.org/config/protocols/socks.html

hysteria 的客户端支持 socks5 作为 inbounds ， 服务端支持 socks5_outbound 。
https://github.com/HyNetwork/hysteria/wiki/%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95

都用 socks5 串联起来即可实现你的需求， 套娃是不建议的。
