### ISSUE TITLE
能连上YouTube，但是看不了视频，VPS端返回tcp error,tcp eof

### ISSUE THREAD

**Issue by giodano0718** [HyNetwork/hysteria#329]
![image](https://user-images.githubusercontent.com/88591600/168612999-a24c1d75-f45b-455c-94c4-7a82d87947e7.png)

老大，先别关了我这个issue，关之前先指点一下怎么破？

**Comment by giodano0718** [comment]
1：![服务端配置](https://user-images.githubusercontent.com/88591600/168629201-badfbbd5-fee3-476c-b428-636e5e651ff8.png)
![客户端配置](https://user-images.githubusercontent.com/88591600/168629212-92b67eed-b6b9-4380-aa2e-0e55fc5fd8cc.png)
2：![VPS输出信息](https://user-images.githubusercontent.com/88591600/168629231-d7805926-2ed1-4b14-91dd-539542722063.png)
3：搭建服务端没用一键脚本：下载acme.sh脚本获取key和证书，下载hysteria-linux-amd64,然后就执行
![00](https://user-images.githubusercontent.com/88591600/168630024-cff70bef-fd1d-42f4-8e3f-443bb96cd073.png)
4：客户端用的是Openwrt里面的passwall
![客户端](https://user-images.githubusercontent.com/88591600/168630390-137181ad-adfe-4b82-a9b0-f2bd48874275.png)
5：本地运营商是中国电信
6：VPS是Cloudcone SC2
7:我用的是win10
大佬看看我提供的信息是不是充足？

**Comment by haruue** [comment]
方便发一下 passwall 配置文件么？

+ 如果你会使用 ssh 或者 WinSCP 访问路由器， 那么 `/etc/config/passwall2` 的内容就是。
+ 如果你不会使用 ssh ， 那么可以从 OpenWRT 左侧菜单的「系统」-「备份/升级」， 点击「生成备份」按钮下载设置备份， 解压你下载的 .tar.gz 压缩文档（可能需要解压两次）， 然后里面也会有个 `etc/config/passwall2` 。

发送之前请检查 passwall2 文件内容， 将服务器地址和各种密码换成 `xxxx` 。

**Comment by haruue** [comment]
需要的是文本文件而不是截图。

**Comment by giodano0718** [comment]
[passwall.txt](https://github.com/HyNetwork/hysteria/files/8705450/passwall.txt)

麻烦帮我检查一下，感谢！

**Comment by chika0801** [comment]
你这个不是应该去passwall发嘛？

**Comment by haruue** [comment]
注意到 `option tcp_node '9af49f27af4842efa80450c634996613'` ，这个 `9af49f27af4842efa80450c634996613` 在你的配置文件中没有对应的节点，你是在导出配置文件之后删除了这个节点吗？ 如果不是的话建议重新选择一下「服务」-「Pass Wall」-「基本设置」-「主要」-「TCP节点」

![image](https://user-images.githubusercontent.com/13131972/168746750-14b815dc-a75d-4376-8ee8-fa887db36943.png)

另外我把 Hysteria 节点换成我自己的测试节点之后一切正常， YouTube 视频也能正常播放， 考虑到 Pass Wall 不显示 Hysteria 客户端的输出。 能不能试试直接在 Windows 上运行 Hysteria ， 通过 HTTP 或者 Socks 代理来使用 Hysteria ， 看看是否正常？

**Comment by haruue** [comment]
经过测试似乎这样配置的话 UDP 会有问题。 这或许能解释 YouTube 无法播放的问题（如果 YouTube 使用 QUIC 来下载视频）。
