### ISSUE TITLE
%USERPROFILE%\.local folder on Windows

### ISSUE THREAD

**Issue by klkq** [HyNetwork/hysteria#332]
When running in server mode, Hysteria generates a folder named `.local` in `%USERPROFILE%` to store data, which should be located in `%APPDATA%` as Windows' convention.

**Comment by haruue** [comment]
Seems like the directory is created by certmagic. I think we can provide an option in "acme" for customizing the certificate storage directory.
https://github.com/caddyserver/certmagic/blob/a48e34ff313ea8d7c84d5c60cd22ba7c1acdee28/filestorage.go#L363-L371

But if you want to change the default behavior, I recommend you to post this issue at certmagic project.

**Comment by klkq** [comment]
Thanks for the information. AFAIK, providing the option might be useful to make the program portable. 
And I have posted the issue to the certmagic project.
