### ISSUE TITLE
请问如何重启服务？

### ISSUE THREAD

**Issue by icecoins** [HyNetwork/hysteria#335]
在服务器上把hy跑起来之后好像两三个小时就会自己关了
在运行期间直接输入hysteria server会因为端口占用不能重启，只能等他自己关了才能重启
但是无法预料它多久会自己关...
请问除了重启服务器外，还有什么命令可以直接重启hy服务的吗？

**Comment by haruue** [comment]
hysteria server 在启动之后不会自动关闭。
能使用 screen 或者 tmux 或者 byobu 这种东西启动 hysteria server 看看退出的时候产生了什么日志么？
如果你是用一键脚本在 VPS 上安装的 hysteria ， 请告诉我们你用的是哪一个一键脚本？

**Comment by icecoins** [comment]
不好意思，原来是服务器太拉胯自己崩溃重启了
打扰了，没有问题了
