### ISSUE TITLE
socks5 建立连接似乎有点慢？

### ISSUE THREAD

**Issue by clz0** [HyNetwork/hysteria#344]
以下结果在Linux本地测试

我连接hysteria的时候，发现建立连接大概需要80-90ms，然而都在本地不该这么慢。
```
google.com:443 ::socks 83.092764ms
```

我测试了别的代理，比如trojan-go，`346.923µs`，这个数值应该是正常的。

**Comment by haruue** [comment]
能不能告诉我们你是如何测试 socks 建立连接所消耗的时间的？ 方便我们重现这个问题。

**Comment by tobyxdd** [comment]
这个连接建立速度是单纯的 TCP 连接建立还是包括了 SOCKS5 request/response?

如果是后者的话，SOCKS5 开在本地，请求还是要发到 hysteria 服务端的。必须等服务端的结果来决定 SOCKS5 状态返回什么，有延迟是正常的。

**Comment by clz0** [comment]
是我在测试我写的透明代理的时候发现的。建立连接指的是socks5握手的时间，不包括请求服务端。
通过curl也能粗略看出时间差异
```
// hysteria
curl -x socks5h://127.0.0.1:10088 https://google.com  0.01s user 0.01s system 4% cpu 0.412 total
// trojan-go
curl -x socks5h://127.0.0.1:10899 https://google.com  0.01s user 0.01s system 4% cpu 0.327 total
```

**Comment by clz0** [comment]
> 如果是后者的话，SOCKS5 开在本地，请求还是要发到 hysteria 服务端的。必须等服务端的结果来决定 SOCKS5 状态返回什么，有延迟是正常的。

原来如此，谢谢解答
