### ISSUE TITLE
https握手延迟3倍的问题

### ISSUE THREAD

**Issue by PHCSJC** [HyNetwork/hysteria#348]
vps的ping延迟是175ms左右，握手延迟的测试方法是httping+google：
httping -g https://www.google.com -c 5
Auto enabling SSL due to https-URL
PING www.google.com:443 (/):
connected to 142.250.68.4:443 (1029 bytes), seq=0 time=540.57 ms 
connected to 142.250.68.4:443 (1254 bytes), seq=1 time=537.73 ms 
connected to 142.250.68.4:443 (1254 bytes), seq=2 time=538.96 ms 
connected to 142.250.68.4:443 (1254 bytes), seq=3 time=541.47 ms 
connected to 142.250.68.4:443 (1254 bytes), seq=4 time=537.50 ms 

测试结果：
hysteria是540ms，正好是ping的3倍，我还做了以下测试：
ss：3倍
ss+tcp fast open模式：2倍
ss+kcptun：2倍
gost的quic模式：3倍
gost的quic+relay：2倍
gost的mws+relay：2倍
v2ray非多路复用：3倍
v2ray多路复用：2倍

这里和hysteria最相似的应该是gost的quic模式，不加relay是3倍，加relay是2倍，不知道这里有没有借鉴意义，来解决hysteria延迟3倍的问题

**Comment by PHCSJC** [comment]
另外，还可以这样测，httping加上tcp fast open，测谷歌的http（不是https）：
httping -g http://www.google.com -c 5 -F
直接说结论：
hysteria是2个RTT
gost的quic+relay是1个RTT

**Comment by PHCSJC** [comment]
还有一种测试方法，dig解析，如：
dig google.com @8.8.8.8 +tcp
结论是：
hysteria是2个RTT
gost的quic+relay是1个RTT

**Comment by haruue** [comment]
能不能用你的理论解释下这个？

```root@hongkong:~ # ping -n4 -c5 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=62 time=1.88 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=62 time=1.92 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=62 time=1.94 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=62 time=1.90 ms
64 bytes from 1.1.1.1: icmp_seq=5 ttl=62 time=1.87 ms

--- 1.1.1.1 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4008ms
rtt min/avg/max/mdev = 1.874/1.901/1.936/0.023 ms
root@hongkong:~ # httping -g https://1.1.1.1 -c 5
Auto enabling SSL due to https-URL
PING 1.1.1.1:443 (/):
connected to 1.1.1.1:443 (1144 bytes), seq=0 time= 29.94 ms 
connected to 1.1.1.1:443 (1142 bytes), seq=1 time= 31.80 ms 
connected to 1.1.1.1:443 (1138 bytes), seq=2 time= 23.11 ms 
connected to 1.1.1.1:443 (1142 bytes), seq=3 time= 21.40 ms 
connected to 1.1.1.1:443 (1146 bytes), seq=4 time= 26.49 ms 
--- https://1.1.1.1/ ping statistics ---
5 connects, 5 ok, 0.00% failed, time 5549ms
round-trip min/avg/max = 21.4/26.5/31.8 ms
```

**Comment by haruue** [comment]
要做到 1xRTT， 确实可以和代理的 server 端的 TCP 连接重用有关， 但是多路复用真的意味着 server 的服务端可以在客户端应用程序要求建立新的 TCP 连接的情况下复用已有连接吗？ 我觉得这样是做不到的。

httping 有个选项 `-Q` 可以让 httping 重用已有连接来进行后续的请求， 这样的话后续请求也是 1xRTT。

```
root@china:~ # httping -g https://1.1.1.1 -c5 -Q
Auto enabling SSL due to https-URL
PING 1.1.1.1:443 (/):
pinged host 1.1.1.1:443 (1143 bytes), seq=0 time=150.82 ms 
pinged host 1.1.1.1:443 (1141 bytes), seq=1 time= 47.67 ms 
pinged host 1.1.1.1:443 (1143 bytes), seq=2 time= 47.99 ms 
pinged host 1.1.1.1:443 (1147 bytes), seq=3 time= 48.23 ms 
pinged host 1.1.1.1:443 (1143 bytes), seq=4 time= 59.43 ms 
--- https://1.1.1.1/ ping statistics ---
5 connects, 5 ok, 0.00% failed, time 5355ms
round-trip min/avg/max = 47.7/70.8/150.8 ms
```

第一次就是 3 倍延迟， 后续就只需 1 倍延迟了。

另外现代的浏览器都会重用已有连接， 所以最后的效果应该也就对这个 Host 的第一次请求会慢一些。

**Comment by haruue** [comment]
> 在session发起前，hysteria自身要消耗掉一个RTT来建立连接，所以任何session的连接都要比正常连接多1个RTT。

这个是正确的。 Hysteria 需要通过 Control Stream 额外发一个请求给服务端要求创建新的连接， 我觉得除非在发出这个请求的同时发送数据， 不然这个是无法优化的。

> 实际访问网页的延迟其实是要多2个RTT，比如访问google，先DNS解析，多1个RTT，再开始建立连接，又多1个RTT，所以实际就是2个RTT，如果vps的延迟是250ms，那由hysteria造成的延迟就是0.5秒，这个时间其实还是比较长的

这个是不一定的， 如果你的浏览器直接通过 Hysteria 客户端提供的 HTTP/SOCKS5 服务来使用 Hysteria， 那么要访问的域名会原样发送给 Hysteria 服务端， 这种情况下 DNS 解析会在服务端完成， 不会在 DNS 解析上浪费 RTT 。 

如果真的要优化对 DNS 的请求， 那可能要考虑特殊处理 DNS 的 UDP 包， 直接把这种请求用 Control Stream 来传输， 这样就有点 dirty 了。

**Comment by PHCSJC** [comment]
@haruue 
我用的是Tproxy模式，所以浏览器还是要先DNS解析一下，才会访问
其实只要解决hysteria多1个RTT的问题，DNS的问题就解决了，因为DNS TCP模式就是0xRTT
gost的quic+relay协议没有多1xRTT的问题，relay协议就是多路复用？不知道对hysteria的优化有没有借鉴意义呢？

**Comment by f4nff** [comment]
我也发现了，hy确实在握手这里速度响应比较慢，
因为hy内部的传输协议是socks5，
socks5握手需要2个rtt，
relay这种，只需要1个，

类似于
hy=socks5，
relay=socks4

**Comment by f4nff** [comment]
[PHCSJC](https://github.com/PHCSJC)

hy类似于gost（socks5+quic）

**Comment by arm64v8a** [comment]
不经过代理的 HTTPS(TLS1.3)请求

1RTT ->SYN <-SYN,ACK 
1RTT ->Ack,Client Hello <-Server Hello
1RTT ->HTTP <-HTTP
=3RTT

然后考虑到google.com一般在翻墙服务器的隔壁机房，延迟可以不计，那么v2ray mux相当于

1RTT ->MuxHeader,ClientHello <-ServerHello
1RTT ->HTTP <- HTTP
=2RTT
~~比你直接连接美国的google.com还要快~~

Hysteria

1RTT (Control Stream) 
1RTT ->Client Hello <-Server Hello
1RTT ->HTTP <-HTTP
=3RTT

所以(首次)打开网站的延迟是2~3倍增长的，想要打开的快还是要找最近的节点。
比如，VPS在美国，175ms，Mux可以把 500ms 多的延迟优化到 350ms
但是如果VPS在日本，70ms，正常打开 210ms，开mux就是140ms

这还没有计DNS的时间，如果是VPN模式，不开fakeDNS的话，这个延迟可能就是4倍以上 :)

**Comment by PHCSJC** [comment]
@arm64v8a 是的，其实就是多1个RTT，虽然hy已经很优秀，但还是希望作者可以优化下

**Comment by PHCSJC** [comment]
看到v1.05已经增加redirect，非常感谢付出，大佬有计划解决一下这个多1xRTT的问题吗？

**Comment by Smallthing** [comment]
> 

能占个地问一下redirect咋用吗
我用ss-redir的方式用，链接不能建立，会EOF

**Comment by flipphos** [comment]
同问，看了wiki感觉没有找到使用方法
能给个范例吗？

**Comment by PHCSJC** [comment]
@Smallthing @flipphos 
redirect和tproxy几乎一样，只是iptables命令不同，另外tproxy可以代理tcp和udp，redirect只能代理tcp，如果你用不到tproxy，也就用不到redirect，配置文件就是将tproxy_tcp修改为redirect_tcp。

**Comment by flipphos** [comment]
多谢！
我的使用场景是先接入HK的hysteria节点，然后转发到终端的US hysteria节点用来看netflix

我用ss是可以实现的。就是想利用hysteria可以对抗较差网络的特性，特别是国内到HK这一段。

**Comment by Smallthing** [comment]
> @Smallthing @flipphos redirect和tproxy几乎一样，只是iptables命令不同，另外tproxy可以代理tcp和udp，redirect只能代理tcp，如果你用不到tproxy，也就用不到redirect，配置文件就是将tproxy_tcp修改为redirect_tcp。

是的 tproxy一切正常 但是我用ss-redir能用的iptables redirect规则 在同一个端口把TCP的端口替换成hysteria的redirect端口.却报错..

**Comment by PHCSJC** [comment]
@Smallthing 配置文件修改了吗？要把tproxy_tcp修改为redirect_tcp

**Comment by Smallthing** [comment]
配置就是这么写的 tcp端口用redirect_tcp
udp端口用tproxy

**Comment by PHCSJC** [comment]
@Smallthing 那就不太清楚了，我这是可以的

**Comment by f4nff** [comment]
作者把内部协议换成relay就可以了，现在内部协议是socks5，所以多了一个rtt

**Comment by PHCSJC** [comment]
@f4nff 可能作者太忙，反馈1个多月了，依然没有任何动静，所以只能尝试找个折中方案

**Comment by f4nff** [comment]
[https://github.com/go-gost/relay](https://github.com/go-gost/relay)

作者把socks5换成 relay即可。

**Comment by tobyxdd** [comment]
我通过 https://github.com/HyNetwork/hysteria/blob/master/docs/socks5/tcping.py 测试并不是 3 RTT 而是 2 RTT 左右（加服务端到 `1.1.1.1` 的延迟），你确定你排除了这部分吗？

**Comment by PHCSJC** [comment]
简化一下测试方法，就以gost的relay+quic为例：
服务端：
gost -L=relay+quic://:555

客户端：
gost -L=redirect://:1090 -F=relay+quic://vpsip:555

apt install httpping -y
httping -g http://1.1.1.1 -c 5
此时就可以看到1xRTT

**Comment by Smallthing** [comment]
> 我通过 https://github.com/HyNetwork/hysteria/blob/master/docs/socks5/tcping.py 测试并不是 3 RTT 而是 2 RTT 左右（加服务端到 `1.1.1.1` 的延迟），你确定你排除了这部分吗？

多种方法测试，确实如PHCSJC所说（我的方法是链接一个延迟1500ms的服务器进行tcp握手测试，多一个RTT非常明显）

**Comment by PHCSJC** [comment]
作者有复现吗？

**Comment by tobyxdd** [comment]
> 1RTT ->MuxHeader,ClientHello <-ServerHello

我还是没明白怎么在第一个 RTT 实现同时发送 MuxHeader 和 ClientHello。以 client 是 SOCKS5 的情况举例，第一个 RTT 不是只能发送 addr 给 server 尝试建立连接，返回状态到 client，client 返回对应 SOCKS5 响应吗？不返回给上层应用 SOCKS5 reply 的话要怎么拿到 ClientHello？

还是你的意思是说 SOCKS5 无论如何都马上返回成功，让客户端把 request 发出来？这样的话地址其实是无效的，服务端没法建立连接的情况怎么办？

**Comment by PHCSJC** [comment]
> 尝试了一个折中方案实现了0xRTT： hysyteria客户端中添加： "relay_tcps": [ { "listen": "127.0.0.1:2222", "remote": "127.0.0.1:2222" } ],
> 
> 服务端下载gost，并启动： gost -L relay+mws://127.0.0.1:2222
> 
> 客户端下载gost，并启动： gost -L=redirect://:1090 -F=relay+mws://127.0.0.1:2222
> 
> 说明一下：gost的relay+mws是0xRTT，再走hysteria通道加速，实测下载速度、y2b速度和单hysteria几乎一样，好处是DNS解析变成了0xRTT，网页打开也会少1个RTT

@tobyxdd 要不看看这个？gost的relay协议就可以实现

**Comment by PHCSJC** [comment]
> 简化一下测试方法，就以gost的relay+quic为例：
> 
> 下载最新的v2.11.2： https://github.com/ginuerzh/gost/releases
> 
> 服务端： gost -L=relay+quic://:555
> 
> 客户端： gost -L=redirect://:1090 -F=relay+quic://vpsip:555
> 
> apt install httping -y httping -g http://1.1.1.1 -c 5 此时就可以看到1xRTT，而hy是2xRTT

@tobyxdd 要不看看这个？gost的relay协议就可以实现

**Comment by tobyxdd** [comment]
> 就是这样

这样的话我不想做。属于不遵守 SOCKS5 规范了

**Comment by f4nff** [comment]
https://github.com/go-gost/relay

作者把socks5换成 relay即可。

**Comment by f4nff** [comment]
我都说过了，socks5握手，本身就多一个rtt，
gost作者搞了一个relay，就不存在这种情况。

**Comment by tobyxdd** [comment]
> 我都说过了，socks5握手，本身就多一个rtt， gost作者搞了一个relay，就不存在这种情况。

我还是没看出来你发的这个 relay 的特别之处，好像也是发一个 request 等 response 吧。是哪里减少了一个 RTT，能解释下吗

**Comment by PHCSJC** [comment]
> 

@tobyxdd 大佬，我不懂代码，没法解释，我实测的确是少一个RTT，要不您先测试一下？测试很简单，按这个步骤要不了5分钟

**Comment by Smallthing** [comment]
> 

是这么回事，所以有空的时候，希望能考虑一下实现一下，就不叫SOCKS5就行了，加个配置flag 写明后果自负。
毕竟一个RTT是实打实的。。

**Comment by Smallthing** [comment]
> > 就是这样
> 
> 这样的话我不想做。属于不遵守 SOCKS5 规范了

尊重作者，是这么回事，有空的时候，还是希望能考虑一下实现一下，就不叫SOCKS5就行了，加个配置flag 写明后果自负。
毕竟一个RTT是实打实的。。

**Comment by PHCSJC** [comment]
同样希望作者能实现，标准不都是人定的吗？也许这就是以后的标准呢，你看http3不就是在追求0-RTT吗？

**Comment by PHCSJC** [comment]
这个问题，作者有计划优化吗？还是不符合标准不做呢？

**Comment by tobyxdd** [comment]
不做
