### ISSUE TITLE
你好，请问有反向链接功能吗？

### ISSUE THREAD

**Issue by snoopy33383622** [HyNetwork/hysteria#350]
请问hysteria有反向连接的功能吗，服务器在内网，无公网端口，想反向连接客户端，请问怎么配置？

**Comment by haruue** [comment]
hysteria 没有自带此功能， 设计上也不会添加此功能（安全考虑， 要是你分享个代理给别人别人瞎转发一堆端口你会舒服？）

不过你可以在连上 hysteria 之后， 本地使用 ssh 通过 hysteria 连接 VPS 做个反代。
VPS 上需要编辑 `/etc/ssh/sshd_config` 取消注释下面这条， 然后重启 ssh 服务。
```
GatewayPorts clientspecified
```

然后本地使用下面这条命令连接 VPS， 你可以还需要一些 `ProxyCommand nc -X connect -x 127.0.0.1:8080 %h %p` 的技巧如果你本地没有配置透明代理。
```
ssh -NR '*:6666:127.0.0.1:2333' root@服务器地址
```
这样访问远程服务器的 6666 接口就是访问本地服务器的 2333 接口。

**Comment by haruue** [comment]
昨天理解错了你的意思。

如果你的「服务器」本身没有公网 IP 地址（例如在一个 NAT 后面）， 而「客户端」有公网 IP 地址， 这种场景现在 Hysteria 并没有支持。

如果不需要穿墙其实直接用 OpenVPN 或者 WireGuard 这样的 Layer 3 VPN 来实现一个 Layer 3 的网络是最简单的。 

实在要使用 Hysteria 的话， 可以考虑在你的「服务端」上运行 hysteria client ， 在「客户端」上运行 hysteria server 。 在你的「服务端」上额外运行一个 http 或者 socks5 代理（例如 privoxy）。 连上之后借助上面提到的 ssh 反向代理转发这个代理的端口， 客户端再使用转发的 http/socks 代理端口来上网。
