### ISSUE TITLE
无法解析config.json文件

### ISSUE THREAD

**Issue by kilvn** [HyNetwork/hysteria#355]
同目录下创建 config.json，用的[这坨](https://github.com/HyNetwork/hysteria/wiki/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8#%E5%AE%A2%E6%88%B7%E7%AB%AF)配置，一直无法启动客户端

[FATA] [file:./config.json] [error:no listen address] Failed to parse server configuration

**Comment by haruue** [comment]
如果你打算启动客户端， 请确认启动命令中不包含 `server` 参数。
