### ISSUE TITLE
同一台VPS，搭建XRay，油管能输出视频画面，搭建Hysteria，无视频画面输出

### ISSUE THREAD

**Issue by giodano0718** [HyNetwork/hysteria#358]
![00](https://user-images.githubusercontent.com/88591600/172966915-b8b9db52-592d-4456-a568-da756aff0e86.png)
两者的配置如下：
![xray](https://user-images.githubusercontent.com/88591600/172967359-817393c8-3dca-4585-85d4-11e176088557.png)

![hysteria](https://user-images.githubusercontent.com/88591600/172967573-b99fc2fc-42c5-44c1-8fd3-a25f07ef1deb.png)
哪位大神能帮忙解释一下这是什么原因？

**Comment by chika0801** [comment]
建议这样排查

不要用路由器翻墙（关插件）

电脑上安v2rayn 测试下故障现象能不能复现了来

**Comment by giodano0718** [comment]
> 建议这样排查
> 
> 不要用路由器翻墙（关插件）
> 
> 电脑上安v2rayn 测试下故障现象能不能复现了来

问题我算是找到了：就是软路由的防火墙规则里面有一条：iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53,我的ADGuard Home要求必须注释掉这一条，否则我的ADG Web端看不到局域网里面的所有客户端，但是就这这一条就会导致Hysteria无视频画面输出；能不能请教一下，怎么样做到两者兼顾？即既让ADG能看到局域网里面所有的客户端，又有Hysteria能输出视频画面？

这是一个比较普遍的问题，能协助解决吗？

**Comment by chika0801** [comment]
我不怎么用路由器翻墙。帮不了你。

**Comment by haruue** [comment]
`iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53` 的作用是重定向你的 lan 的所有 DNS 请求到你的路由器， 如果没有这条 iptables ， 将你的 PC 的网络属性里的 DNS 设置成你的路由器地址应该能达到相同的效果。

另外， 在视频无法播放的情况下， 你可以按 F12 打开浏览器的开发者工具， 选择 Network 选项卡， 然后尝试刷新页面来检查哪些请求加载失败。

**Comment by giodano0718** [comment]
![01](https://user-images.githubusercontent.com/88591600/173170893-225c06dd-2a61-4cd8-abf5-e7d74eebe665.png)
![02](https://user-images.githubusercontent.com/88591600/173170894-2234ecb5-7da0-449b-862a-7426a6c5046a.png)
@haruue 按照您说的，加载失败看到这些报错，能帮忙解决一下吗？我是外行 不懂代码

**Comment by haruue** [comment]
这个证书错误显然是你删除了那条重定向 DNS 的 iptables 规则， 导致你无法绕过 GFW 的 DNS 污染。 
我不用 ADGuard 所以不懂它的配置……
此问题和 Hysteria 无关， 这是你 DNS 配置的问题。
不过你可以检查一下自己的 DNS 设置， 把你的 DNS 设置成路由器的地址试试。
