### ISSUE TITLE
探讨一下负载均衡

### ISSUE THREAD

**Issue by f4nff** [HyNetwork/hysteria#363]
起初我想的负载是，**通过间隔测试，或者心跳，判断当前链路的延时满足设定值的范围，**
如果超过范围，就判断当前节点死亡，进行休眠。
但是经过实际测试，有时候节点延时并没浮动，只不过开始丢包。

**1：判断节点是否超时，判断节点是否死亡
2：节点范围的延时在某个设置范围内，以此判断路由有没有切到烂路由。
2：判断当前节点丢包率，丢包率达到某个范围，标记当前节点死亡，设置一个死亡周期。**

**Comment by f4nff** [comment]
基于udp协议，确实要比tcp快，尤其响应这块，
但是udp也比较挑，有些区域的运营商对udp很不友好，这个无解。

以上先不说，就是负载了，如果链路出问题，每次都需要进行手动排查，才可以判断出线路是否出问题。

需要手动切换，这个很烦躁。

**Comment by tobyxdd** [comment]
hysteria 本身不计划添加此类功能。如有需要建议用 clash.meta 这类整合了 hy 的客户端

**Comment by xiaorong61** [comment]
> 基于udp协议，确实要比tcp快，尤其响应这块， 但是udp也比较挑，有些区域的运营商对udp很不友好，这个无解。
> 
> 以上先不说，就是负载了，如果链路出问题，每次都需要进行手动排查，才可以判断出线路是否出问题。
> 
> 需要手动切换，这个很烦躁。

换到 bbr 模式试试
