### ISSUE TITLE
CryptAcquireContext failed with error -2146893809

### ISSUE THREAD

**Issue by lll423** [HyNetwork/hysteria#366]
CryptAcquireContext failed with error -2146893813, trying to create NEWKEYSETAssertion "CryptAcquireContext failed with error -2146893809" failed at line 70 in /go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/c/custom/sys_arch.c

这个是什么情况

**Comment by hulisang** [comment]
我也是这样

**Comment by daoke1504** [comment]
win10 版本号21H2 内部版本19044.1766   相同问题。

**Comment by tobyxdd** [comment]
dup of https://github.com/HyNetwork/hysteria/issues/293
