### ISSUE TITLE
sysctl: cannot stat /proc/sys/net/core/rmem_max: No such file or directory

### ISSUE THREAD

**Issue by rkygogo** [HyNetwork/hysteria#369]
Lxc与openvz架构的vps出现这个报错！

**Comment by kinsan2007** [comment]
openvz：
cat: /proc/sys/net/core/rmem_max: No such file or directory
kvm：
cat /proc/sys/net/core/rmem_max
212992
记得是说openvz的修改权限很小，只能更具母根据母鸡的设置来，我的记法：和内核优化有关的openvz都不行，更可笑的是有次openvz 安装v2ray，可是时间不对，我都没权修改，需要发工单，呵呵。

**Comment by haruue** [comment]
Hysteria 或者 Hysteria 的依赖里并没有强制需要修改 `net.core.rmem_max` 的代码， 我们只是在 Wiki 里提了一句 [对于超高速连接的情况下可以通过修改这个选项来优化](https://github.com/HyNetwork/hysteria/wiki/%E4%BC%98%E5%8C%96) ， 但是对于大部分 OpenVZ 或者 LXC 服务商其实用不上这个。
 
请问你是在使用哪个一键脚本的时候看到的这个报错吗？ 请提供你使用的一键脚本的版本或者直接把它让你执行的命令复制到这里。

如果你只是按照互联网上的某个教程一行行地执行命令来配置 Hysteria 服务端， 这个报错直接忽略即可， 不影响 Hysteria 的运行。

如果不是上述情况， 请提供一下详细的报错日志或者截图。

**Comment by haruue** [comment]
> @rkygogo: https://github.com/emptysuns/Hi_Hysteria/blob/main/server/install.sh 693行 sysctl -w net.core.rmem_max=8000000 此命令一输入就会报这个错。。。

报这个错应该不会影响 Hysteria 服务端正常运行， 如果你的 shell 设置导致你因此无法继续运行这行脚本， 直接删除/注释这一行即可。
