### ISSUE TITLE
openwrt中编译报错

### ISSUE THREAD

**Issue by rosewu550** [HyNetwork/hysteria#371]
报错日志：
Building targets
package github.com/tobyxdd/hysteria/cmd
imports github.com/tobyxdd/hysteria/pkg/tun
imports github.com/eycorsican/go-tun2socks/tun: build constraints exclude all Go files in /home/wuwei/openwrt/lede/dl/go-mod-cache/github.com/eycorsican/go-tun2socks@v1.16.11/tun

make[3]: *** [Makefile:56: /home/wuwei/openwrt/lede/build_dir/target-x86_64_musl/hysteria-1.0.5/.built] Error 1
make[3]: Leaving directory '/home/wuwei/openwrt/lede/feeds/small/hysteria'
time: package/feeds/small/hysteria/compile#0.59#0.20#0.35
ERROR: package/feeds/small/hysteria failed to build.
make[2]: *** [package/Makefile:116: package/feeds/small/hysteria/compile] Error 1
make[2]: Leaving directory '/home/wuwei/openwrt/lede'
make[1]: *** [package/Makefile:110: /home/wuwei/openwrt/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/wuwei/openwrt/lede'
make: *** [/home/wuwei/openwrt/lede/include/toplevel.mk:230: world] Error 2

**Comment by haruue** [comment]
能不能给一下你使用的 OpenWRT 源码仓库或者 OpenWRT SDK 下载链接。 我不认为在 OpenWRT 上编译 Hysteria 会产生这个问题。

**Comment by rosewu550** [comment]
> 能不能给一下你使用的 OpenWRT 源码仓库或者 OpenWRT SDK 下载链接， 以及编译配置文件（编译环境根目录的 `.config` ）。 我不认为在 OpenWRT 上编译 Hysteria 会产生这个问题。
[config.txt](https://github.com/HyNetwork/hysteria/files/9033906/config.txt)

我用的是l大（https://github.com/coolsnowwolf/lede）master分支最新的源码编译的

**Comment by rosewu550** [comment]
我自己的问题，删除dl/go-mod-cache后，重新编译就好了
