### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by asusdong** [HyNetwork/hysteria#373]
windows客户端报错   [ERRO] [error:timeout: no recent network activity] [0mFailed to initialize client 求大神告知解决方法

**Comment by haruue** [comment]
请先根据 Wiki 排查
https://github.com/HyNetwork/hysteria/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#erro-errortimeout-no-recent-network-activity
