### ISSUE TITLE
已经检查过混淆密码和端口都没错

### ISSUE THREAD

**Issue by asusdong** [HyNetwork/hysteria#374]
请先根据 Wiki 排查
https://github.com/HyNetwork/hysteria/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#erro-errortimeout-no-recent-network-activity

_Originally posted by @haruue in https://github.com/HyNetwork/hysteria/issues/373#issuecomment-1179676078_

**Comment by haruue** [comment]
请提供一下你服务器的配置文件和客户端配置文件（可以移除服务器地址等敏感信息）， 如果你使用一键配置脚本或者定制客户端（像 passwall 或者 clash）， 也请说一下。

另外这还新开一个 issue ， 即使是已关闭 issue 也可以继续回复和 reopen 的。

**Comment by asusdong** [comment]
配置文件

Haruue ***@***.***> 于2022年7月10日周日 16:21写道：

**Comment by haruue** [comment]
没看到你的回复里有配置文件， 可能你发送的附件被你的邮件客户端吃掉了， 能登录 GitHub 回复或者直接把配置文件复制粘贴到邮件里么？

**Comment by asusdong** [comment]
重置了系统之后重新安装问题解决了，谢谢你热心帮助。

Haruue ***@***.***> 于2022年7月10日周日 21:49写道：
