### ISSUE TITLE
hysteria为何会像52.69.239.207日本的ip地址443端口发送数据？

### ISSUE THREAD

**Issue by kyohan789** [HyNetwork/hysteria#377]
hysteria为何会像52.69.239.207日本的ip地址443端口发送数据？

![image](https://s3.bmp.ovh/imgs/2022/07/14/1fdbad4f52dc03ec.bmp)
![image](https://s3.bmp.ovh/imgs/2022/07/14/a102092cfd6bf601.bmp)

**Comment by mritd** [comment]
你的截图没有任何有用信息, 请证明是由 hy 发送

**Comment by haruue** [comment]
经查这是 hysteria 内置的更新检测功能发出的请求

https://github.com/HyNetwork/hysteria/blob/9f406531914728b43801768409a7b206353b4620/cmd/update.go#L12

```
api.github.com.         39      IN      A       52.69.239.207
```

该功能可在命令行中关闭。
