### ISSUE TITLE
"max_conn_client": 4096, // 单客户端最大活跃连接数

### ISSUE THREAD

**Issue by liuxyon** [HyNetwork/hysteria#381]
"max_conn_client": 4096, // 单客户端最大活跃连接数

我不太理解这个参数具体含义. 是指同一个密码登陆的客户端数还是什么？

因为我希望能约束用户同时登陆个数，即给一个用户配置，不希望他散发给很多人用. 
但是我测试 将此参数改为 1-5 都是不能正常连接工作，改为10可以工作. 所以我想了解此参数具体含义？

**Comment by tobyxdd** [comment]
指的是一个客户端（一个人开一个客户端算一个；一个人开两个客户端算两个；两个人各开一个也算两个；总之和验证没关系）最多能同时发起多少个活跃 TCP 连接。

**Comment by liuxyon** [comment]
> 指的是一个客户端（一个人开一个客户端算一个；一个人开两个客户端算两个；两个人各开一个也算两个；总之和验证没关系）最多能同时发起多少个活跃 TCP 连接。

实际如果设置1,客户端是无法连接的. udp模式.

**Comment by PanHsin** [comment]
或许没理解活跃连接数的概念，
作者最后那句解释应该就是核心，是指最大活跃的tcp连接数。不看什么客户端数量，参数的目的也不是客户端数量，，无论多少个客户端，累计的连接数不能超过这个设定数量。设定为1没有意义，或只设定个位数。实际的活跃连接数没那么少，设定值不合理，当然没法连接。
