### ISSUE TITLE
[Help me] Optimal recv_window value

### ISSUE THREAD

**Issue by humblebeee** [HyNetwork/hysteria#383]
### Details

I have deployed Hysteria on my server and so far I'm very happy about it, it's easier to setup than Shadowsocks and faster too! The only issue I'm expriencing is that data flow stops intermittently, like I'm streaming a song on Spotify and every now and then it stops for 30-60 seconds and resumes again! 

I'm on a DSL connection with 16 Mbps download and 2 Mbps upload, my server has a 100 Mbps connection speed, I was wondering if tinkering with `recv_window` values would help this issue but I'm not sure what to set for the above mentioned speeds.

### Server-side hysteria or scripts information

1.1.0

### VPS information

Ubuntu 20.04, Intel Xeon 1 core, 512MB

### Server-side configuration
```
{
    "listen": ":443",
    "protocol": "udp",
    "cert": "/etc/letsencrypt/live/xxxfullchain.pem",
    "key": "/etc/letsencrypt/live/xxx/privkey.pem",
    "obfs": "mykey",
    "up_mbps": 100,
    "down_mbps": 100,
    "max_conn_client": 1024,
    "resolver": "1.1.1.1:53",
    "resolve_preference": "46"
}
```
### Server-side logs
```
Hysteria  | 2022-07-27T20:39:26Z [INFO] [config:{Listen::443 Protocol:udp ACME:{Domains:[] Email: DisableHTTPChallenge:false DisableTLSALPNChallenge:false AltHTTPPort:0 AltTLSALPNPort:0} CertFile:/etc/letsencrypt/live/xxx/fullchain.pem KeyFile:/etc/letsencrypt/live/xxx/privkey.pem Up: UpMbps:100 Down: DownMbps:100 DisableUDP:false ACL: MMDB: Obfs:mykey Auth:{Mode: Config:[]} ALPN: PrometheusListen: ReceiveWindowConn:0 ReceiveWindowClient:0 MaxConnClient:1024 DisableMTUDiscovery:false Resolver:1.1.1.1:53 ResolvePreference:46 SOCKS5Outbound:{Server: User: Password:} BindOutbound:{Address: Device:}}] Server configuration loaded
Hysteria  | 2022-07-27T20:39:26Z [INFO] [addr::443] Server up and running
```
### Client-side hysteria information

1.1.0

### Client-side configuration
```
{
    "server": "example.com:443",
    "server_name": "example.com",
    "protocol": "udp",
    "obfs": "mykey",
    "up_mbps": 2,
    "down_mbps": 16,
    "retry": 10,
    "retry_interval": 10,
    "socks5": {
        "listen": "127.0.0.1:1080"
    },
    "http": {
        "listen": "127.0.0.1:3128"
    }
}
```

### Client-side environment (operating system)

Ubuntu 22.04

### Client-side logs
```
Hysteria  | 2022-07-28T11:57:17+04:30 [INFO] [config:{Server:example.com:443 Protocol:udp Up: UpMbps:2 Down: DownMbps:16 Retry:10 RetryInterval:10 SOCKS5:{Listen:127.0.0.1:1080 Timeout:0 DisableUDP:false User: Password:} HTTP:{Listen:127.0.0.1:3128 Timeout:0 User: Password: Cert: Key:} TUN:{Name: Timeout:0 Address: Gateway: Mask: DNS:[] Persist:false} TCPRelays:[] TCPRelay:{Listen: Remote: Timeout:0} UDPRelays:[] UDPRelay:{Listen: Remote: Timeout:0} TCPTProxy:{Listen: Timeout:0} UDPTProxy:{Listen: Timeout:0} TCPRedirect:{Listen: Timeout:0} ACL: MMDB: Obfs:mykey Auth:[] AuthString: ALPN: ServerName:example.com Insecure:false CustomCA: ReceiveWindowConn:0 ReceiveWindow:0 DisableMTUDiscovery:false Resolver: ResolvePreference:}] Client configuration loaded
Hysteria  | 2022-07-28T11:57:17+04:30 [INFO] [addr:example.com:443] Connected
Hysteria  | 2022-07-28T11:57:17+04:30 [INFO] [addr:127.0.0.1:3128] HTTP server up and running
Hysteria  | 2022-07-28T11:57:17+04:30 [INFO] [addr:127.0.0.1:1080] SOCKS5 server up and running
```

**Comment by chika0801** [comment]
我猜测可能修改那个值帮不了你。

在我们这里DSL连接已经没有人再使用了。

**Comment by humblebeee** [comment]
> 我猜测可能修改那个值帮不了你。
> 
> 在我们这里DSL连接已经没有人再使用了。

English please! I don't speak Chinese! This is GitHub people!

**Comment by tobyxdd** [comment]
You only need to tinker with `recv_window` when the default value is limiting your speed (usually 1Gbps+ which is certainly not the case here). If you are having intermittent connection issues I would suspect more than anything that your ISP or hosting provider has some kind of restrictions on UDP traffic.

Have you tried `fake_tcp` mode, and does it have the same problem?

**Comment by humblebeee** [comment]
> You only need to tinker with `recv_window` when the default value is limiting your speed (usually 1Gbps+ which is certainly not the case here). If you are having intermittent connection issues I would suspect more than anything that your ISP or hosting provider has some kind of restrictions on UDP traffic.
> 
> Have you tried `fake_tcp` mode, and does it have the same problem?

You were right! My ISP is throttling UDP traffic, as soon as I switched to `faketcp`, disconnections dropped to maybe once every now and then! Thank you! So if I got this right, `faketcp` is UDP disguised as TCP traffic?

**Comment by haruue** [comment]
> So if I got this right, `faketcp` is UDP disguised as TCP traffic?

Correctly.

https://github.com/HyNetwork/hysteria/wiki/Advanced-Usage#fake-tcp--tcp-masquerade
> ### Fake TCP / TCP masquerade
> Certain networks may impose various restrictions on UDP traffic or block it altogether. Hysteria offers a "faketcp" mode that allows servers and clients to communicate using a protocol that looks like TCP but does not actually go through the system TCP stack. This tricks whatever middleboxes into thinking it's actually TCP traffic, rendering UDP-specific restrictions useless.
