### ISSUE TITLE
大流量使用持续3—5秒会断开重连

### ISSUE THREAD

**Issue by xcf13363175** [HyNetwork/hysteria#384]
使用openwrt+SSRP+hysteria在大流量下载3—5秒后会丢失连接。
UDP和wechat模式都一样。
不知道是不是个例

**Comment by chika0801** [comment]
我路由器AX6 ssrp最新版本 hy 1.1 不同VPS没复现

**Comment by tobyxdd** [comment]
这应该是你硬件、ISP、VPS 商之一的问题导致的
