### ISSUE TITLE
建議增加FreeBSD版本打包

### ISSUE THREAD

**Issue by money-finder** [HyNetwork/hysteria#385]
### 功能描述

部分網路設備基於FreeBSD，建議增加該分支版本的打包，以便在FreeBSD網路設備上直接使用

### 这个功能的必要性

如果增加該分支的打包，程序將能運行在OPNSense、PfSense等防火牆系統上，甚至可以考慮加入該類系統的應用商店進行分發，增加Hysteria的普及度及方便程度

### 当前可用的替代方案

因為無法運行在該系統上，所以需要額外接入網件單獨運行Hysteria，較為麻煩且多餘

**Comment by liuxyon** [comment]
支持, 建议同时和支持bgp tun功能一起加入. 目前使用pfsense. 但未来可能转opnsense.
这样是不是还要添加web 界面？

**Comment by money-finder** [comment]
> 支持, 建议同时和支持bgp tun功能一起加入. 目前使用pfsense. 但未来可能转opnsense. 这样是不是还要添加web 界面？

感覺並不需要專門為freebsd類系統專門添加web ui，當然作者如果站在更高層面決定這麼做也不錯。

現在用的其他類似hysteria的工具，在freebsd上也沒有專門的配置界面，但因為其已為freebsd專門打包，copy個配置文件就能直接跑，運行得不錯。

**Comment by haruue** [comment]
特定的 Linux 或者 FreeBSD 发行版（如 pfsense）是否收录 Hysteria 的二进制包， 这是由下游决定的， 而不是由我们决定的。

举个例子， pfsense 的构建脚本是在 [这个仓库](https://github.com/pfsense/FreeBSD-ports)， 你可以在里面找到其它类似工具的编译脚本， 例如 [shadowsocks](https://github.com/pfsense/FreeBSD-ports/tree/devel/net/shadowsocks-libev) 或者 [v2ray](https://github.com/pfsense/FreeBSD-ports/tree/devel/net/v2ray)， 因此才会构建出软件包并通过系统自带的软件包管理工具进行提供。 

如果你希望某个特定的 Linux 或者 FreeBSD 发行版能够收录 Hysteria 的二进制包， 你应该考虑向下游或者下游的某个第三方软件仓库（比如 macOS 上的 homebrew）提交收录请求。

**Comment by tobyxdd** [comment]
21382fe39cb3c076b52c6b877eff8a097fffbb13

**Comment by liuxyon** [comment]
> 特定的 Linux 或者 FreeBSD 发行版（如 pfsense）是否收录 Hysteria 的二进制包， 这是由下游决定的， 而不是由我们决定的。
> 
> 举个例子， pfsense 的构建脚本是在 [这个仓库](https://github.com/pfsense/FreeBSD-ports)， 你可以在里面找到其它类似工具的编译脚本， 例如 [shadowsocks](https://github.com/pfsense/FreeBSD-ports/tree/devel/net/shadowsocks-libev) 或者 [v2ray](https://github.com/pfsense/FreeBSD-ports/tree/devel/net/v2ray)， 因此才会构建出软件包并通过系统自带的软件包管理工具进行提供。
> 
> 如果你希望某个特定的 Linux 或者 FreeBSD 发行版能够收录 Hysteria 的二进制包， 你应该考虑向下游或者下游的某个第三方软件仓库（比如 macOS 上的 homebrew）提交收录请求。
> 
> 我们能做的， 最多只是向 GitHub Release 添加通用的二进制构建。

我给opnsense作者介绍了. 你们可以联系看看
