### ISSUE TITLE
发现一个新的windows及linux图形界面代理客户端项目支持hysteria作为内核

### ISSUE THREAD

**Issue by egg1234** [HyNetwork/hysteria#403]
项目地址 https://github.com/MatsuriDayo/nekoray

举例在windows的nekoray界面里面选 程序->首选项->基本设置->核心（添加hysteria.exe）

然后在 服务器->手动输入配置->类型选hysteria ，然后会弹出图形化设置界面，
这里要注意 “地址” 及 “端口” 的框框一定要写你自己的hysteria的服务器域名或ip地址，端口号
把框框原来的127.0.0.1及1080替换掉，右面填好你hysteria服务器连接相应的参数，然后点“生成配置”，然后再点确定即可

暂时hysteria协议只支持系统代理模式，与v2rayN一样，不支持nekoray的vpn模式即整机科学上网模式，但vmess，vless，socks5协议是支持nekoray的vpn模式

至于绕过模式是在 首选项->路由vpn设置->点弹出画面的“预设”就可以选择

重点提示：vpn模式必须在 首选项->路由vpn设置 的画面右上角 勾选“FakeDNS” 就能防止在VPN模式下的DNS泄漏，
另外必须设置 首选项->路由vpn设置 的画面左上角的“域名策略”选择“IPIfNonMatch”，
否则访问国内某些网站会测试出代理服务器的IP地址，但是使用国内的DNS服务器，这个更危险，
在系统代理模式下上面两个设置项其实都用缺省的就好，nekoray本身分流做得非常好
当然这个对于hysteria协议还用不到，因为hysteria协议还不支持vpn模式

另外一定要在 程序->当前服务器那里勾选代理服务器名字，否则程序缺省是没有选定任何服务器的

**Comment by hyyz17200** [comment]
感谢分享，测试了一下是可以的。我用的分享链接添加，感觉更简单些。

**Comment by tobyxdd** [comment]
Thanks for the feedback. NekoRay is now [added to our wiki](https://github.com/HyNetwork/hysteria/wiki/Installation#windows-linux-macos-clients).
