### ISSUE TITLE
[功能请求] 添加对UDS (Unix Domain Socket) 的支持

### ISSUE THREAD

**Issue by HeXis-YS** [HyNetwork/hysteria#406]
### 功能描述

添加UDS作为一种可选的入站/出站方式。

### 这个功能的必要性

作为一种进程间通信，UDS不使用网络底层协议来通信。因此，它相比于TCP Loopback具有更低的延迟（无需握手），更大的吞吐量（不需要拥塞控制、流量控制等）和更低的系统开销。
此功能主要用于配合V2Ray/nginx等工具实现复杂的分流等操作。

**Comment by ddk2222-luck** [comment]
windows就没办法用了，只能在软路由器和服务器上了。

**Comment by f4nff** [comment]
垃圾，分流最稳定的是route

**Comment by haruue** [comment]
用我家有的设备测试了下回环网络的速率和延时。

| CPU | Broadcom BCM4708 | Intel J-1900 | AMD 3970X |
|--------|-----------------------------|-----------------|-----------------|
| 速率 | 1.09 Gbps                 | 8.40 Gbps   | 45.4 Gbps   |
| 延时 | 0.307 ms                   | 0.123 ms     | 0.023 ms     |

回环网络已经足够快了， 我不认为相比 Hysteria 所针对的恶劣网络环境的带宽和延迟来说（例如「卫星网络、拥挤的公共 Wi-Fi、在中国连接国外服务器等」）， 优化回环网络 overhead 能带来多少性能提升。

另外， v2fly 文档里也说了后续他们的 DomainSocket 今后可能会弃用。
https://www.v2fly.org/config/transport/domainsocket.html

如果你是有非常多线路， 在本地端口的分配上感到为难所以才打算求助于 unix domain socket 的话， 请注意除了 `127.0.0.1` 之外， `127.0.0.0/8` 里的任何一个 IP 的任何端口（例如 `127.114.51.4:1919`）都是能够绑定和用作本地通信的， 而 `127.0.0.0/8` 里面有多达 16777214 个可用 IP， 也就是至少 16777214 * 65535 == 1099494719490 个可用端口。
