### ISSUE TITLE
[功能请求] 把内部传输协议从socks5替换为relay

### ISSUE THREAD

**Issue by f4nff** [HyNetwork/hysteria#414]
### 功能描述

把内部传输协议从socks5替换为relay

[https://github.com/go-gost/relay](https://github.com/go-gost/relay)

### 这个功能的必要性

可以降低一个RTT，在握手的时候会减少一个RTT，
在看视频的时候，比如谷歌的youtube，采用的quic协议，
他有个视频清晰度选择，就是按照握手的延时进行判断，而非带宽。

降低一个RTT体验会明显上升，可以直接转发dns 8.8.8.8:53

nslookup www.qq.com

会明显快！

**Comment by haruue** [comment]
https://github.com/HyNetwork/hysteria/issues/348#issuecomment-1184023891
> > 我都说过了，socks5握手，本身就多一个rtt， gost作者搞了一个relay，就不存在这种情况。
> 
> 我还是没看出来你发的这个 relay 的特别之处，好像也是发一个 request 等 response 吧。是哪里减少了一个 RTT，能解释下吗

所以能先回答一下 tobyxdd 之前提出过的这个问题吗？

首先 Hysteria 根本没有所谓的「内部协议是 socks5」 这样的设计， 你需要讲清楚 relay 是如何省下 1xRTT 的， 我们才可能参考你提出的方案来改进 Hysteria 客户端与服务端的通讯方式（前提是不产生 break change）。

如果你根本看不懂 relay 的实现， 就请不要提这种 Feature Request。

**Comment by f4nff** [comment]
```
root@OpenWrt:~/hy# time dig www.qq.com

; <<>> DiG 9.18.1 <<>> www.qq.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49624
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.qq.com.                    IN      A

;; ANSWER SECTION:
www.qq.com.             83      IN      CNAME   ins-r23tsuuf.ias.tencent-cloud.net.
ins-r23tsuuf.ias.tencent-cloud.net. 94 IN A     129.226.102.190
ins-r23tsuuf.ias.tencent-cloud.net. 94 IN A     129.226.106.167

;; Query time: 379 msec
;; SERVER: ::1#53(::1) (UDP)
;; WHEN: Sat Aug 27 18:16:41 UTC 2022
;; MSG SIZE  rcvd: 119

real    0m 0.40s
user    0m 0.01s
sys     0m 0.00s
```

 ```
 "tun": {
    "name": "tun0",
	"timeout": 60,
    "persist": false

  },
  "relay_tcps": [
    {
      "listen": "0.0.0.0:53", 
      "remote": "1.1.1.1:53", 
      "timeout": 60 
    }
  ],
   "relay_udps": [
    {
      "listen": "0.0.0.0:53", 
      "remote": "8.8.8.8:53",
      "timeout": 60 
    }
  ],
```

我这是端口转发模式，可以看到查询的延时是379 ms，我到节点的延时是170ms，
查询延时是170*2+

**Comment by f4nff** [comment]
```
root@OpenWrt:~/hy# time dig www.qq.com +tcp

; <<>> DiG 9.18.1 <<>> www.qq.com +tcp
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1051
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;www.qq.com.                    IN      A

;; ANSWER SECTION:
www.qq.com.             295     IN      CNAME   news.qq.com.edgekey.net.
news.qq.com.edgekey.net. 21595  IN      CNAME   e6156.dscf.akamaiedge.net.
e6156.dscf.akamaiedge.net. 15   IN      A       184.28.246.218

;; Query time: 379 msec
;; SERVER: ::1#53(::1) (TCP)
;; WHEN: Sat Aug 27 18:18:56 UTC 2022
;; MSG SIZE  rcvd: 128

real    0m 0.39s
user    0m 0.00s
sys     0m 0.01s
```

**Comment by f4nff** [comment]
同样的线路，我使用gost的relay+mws模式。

```
./gost  -L=relay+mws://:2211 -D
./gost -L=udp://:1122/1.1.1.1:53 -F=relay+mws://cache.711mb.xyz:2211
```

```
root@OpenWrt:~/hy# time dig www.qq.com  -p 1122 @127.0.0.1

; <<>> DiG 9.18.1 <<>> www.qq.com -p 1122 @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58710
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;www.qq.com.                    IN      A

;; ANSWER SECTION:
www.qq.com.             298     IN      CNAME   news.qq.com.edgekey.net.
news.qq.com.edgekey.net. 21598  IN      CNAME   e6156.dscf.akamaiedge.net.
e6156.dscf.akamaiedge.net. 18   IN      A       184.28.246.218

;; Query time: 199 msec
;; SERVER: 127.0.0.1#1122(127.0.0.1) (UDP)
;; WHEN: Sat Aug 27 18:29:41 UTC 2022
;; MSG SIZE  rcvd: 128

real    0m 0.22s
user    0m 0.01s
sys     0m 0.00s
```

端口转发模式，
可以看到查询延时只有199ms

也就是正常ping的延时+

<img width="492" alt="image" src="https://user-images.githubusercontent.com/19538878/187043583-fa8209fb-5de7-4cd7-940f-d053d3fc6ae5.png">

**Comment by haruue** [comment]
这些测试结果我看你发了好几遍了。
希望你能直接告诉我们 relay 是如何做到这一点的。
这样我们才可能参照着改进。

**Comment by f4nff** [comment]
服务端到dns1.1.1.1的延时8ms，
本地到服务端延时是170ms+

===============================
使用hysteria端口模式查询dns，都在170ms*2+
![image](https://user-images.githubusercontent.com/19538878/187043760-fbd4d837-c2cb-4842-adc1-a5bacecb82d0.png)


============================================

如果使用gost的 relay+mws协议，查询时长在170ms+
```
./gost -L=relay+mws://:2211 -D

./gost -L=udp://:1122/1.1.1.1:53 -F=relay+mws://cache.721mb.xyz:2211
```
![image](https://user-images.githubusercontent.com/19538878/187043750-92961782-3789-4d54-b89b-d588b0dbcd30.png)

===============================
如果使用gost的 socks5+mws协议，查询时长在799ms+

```
./gost -L=mws://:2211 -D
./gost -L=udp://:1122/1.1.1.1:53 -F=mws://cache.17m22b.xyz:2211
```

<img width="524" alt="image" src="https://user-images.githubusercontent.com/19538878/187043704-6cc1bb43-b94d-418d-ae0b-baddf98921c3.png">

==================================

**Comment by f4nff** [comment]
之前不是我发的，是另外一个人发的，那个人也发现了这样的问题。

具体怎么做我就不知道了。

具体能告诉你的，确实存在这样的问题。

区别你可以参照gost-relay的做法。

=====================================
./linux-x64 -L=relay+mws://:2211 -D

./linux-arm -L=udp://:1122/1.1.1.1:53 -F=relay+mws://cache.117mb.xyz:2211

================================================
./linux-x64 -L=mws://:2211 -D

./linux-arm -L=udp://:1122/1.1.1.1:53 -F=mws://cache.117mb.xyz:2211
==============================================

hysteria确实很赞。

**Comment by haruue** [comment]
如果你根本看不懂 relay 的实现， 就请不要提这种 Feature Request。

**Comment by f4nff** [comment]
我只是提出可以改进的方向，不要搞得我不懂怎么做，就让人闭嘴的错觉。

**Comment by f4nff** [comment]
`我还是没看出来你发的这个 relay 的特别之处，好像也是发一个 request 等 response 吧。是哪里减少了一个 RTT，能解释下吗`

你看不懂哪里少了一个rtt，然后我证明给你看，
然后~~

**Comment by PHCSJC** [comment]
@haruue 我们只是hysteria的一个普通使用者，不懂开发和代码，只是会用而已，然后又实测出了relay的确少一个RTT，你非要问我们relay怎么实现的，说不出来就别提这问题，是不是有点难为人呢？
