### ISSUE TITLE
[Feature Request] 增加daemon模式,别让一个cmd窗口在任务栏下

### ISSUE THREAD

**Issue by trekGriffin** [HyNetwork/hysteria#415]
### Feature Details

任务栏下占用一个窗口很烦. 让它有后台运行的能力. 

### The necessity of this feature

necessary

### Available alternative

使用另外的程序把这个cmd窗口最小化到通知栏那里,但是不方便.

**Comment by haruue** [comment]
Duplicated #158

不需要其他程序， 用一个 VBS 脚本就可以了。

**Comment by trekGriffin** [comment]
thanks.  get新能力
