### ISSUE TITLE
Crypto Go ：we are a research group to help developers build secure applications.

### ISSUE THREAD

**Issue by 1047261438** [HyNetwork/hysteria#416]
### Feature Details

Hi, we are a research group to help developers build secure applications. We designed a cryptographic misuse detector (i.e., CryptoGo) on Go language. We found your great public repository from Github, and several security issues detected by CryptoGo are shown in the following. 

### The necessity of this feature

Note that the cryptographic algorithms are categorized with two aspects: security strength and security vulnerability based on NIST Special Publication 800-57 and other public publications. Moreover, CryptoGo defined certain rules derived from the APIs of Go cryptographic library and other popular cryptographic misuse detectors. The specific security issues we found are as follows:
Location: cmd/client.go:40; 
Broken rule: R-11: SSL/TLS use insecure verification;
 We wish the above security issues could truly help you to build a secure application. If you have any concern or suggestion, please feel free to contact us, we are looking forward to your reply. Thanks.

**Comment by haruue** [comment]
The cmd/client.go:40 is
https://github.com/HyNetwork/hysteria/blob/f7de18fd43b2fb8d23c3988793f039173fb4decd/cmd/client.go#L40

There is nothing related to "SSL/TLS use insecure verification".

I think the actually related issue is hysteria provided a options named `"insecure"` that used to "Ignore all certificate errors", please note this options is disable by default and not-recommended. But some hysteria users still need this options to simply their configuration, and they always use this option with `"obfs"` which make the MITM nearly impossible.

And I check the issues you created, there is too much false positive like this one. Please stop sending those spam issues on the GitHub before got your own program works properly.
