### ISSUE TITLE
[请求帮助] 客户端，同样的配置文件，debian11正常，openwrt19.07报错

### ISSUE THREAD

**Issue by rankaiyx** [HyNetwork/hysteria#419]
### 问题详情

debian11客户端用的是hysteria-linux-amd64 v1.2，能正常代理
openwrt19客户端用的是hysteria-linux-386 v1.2，启动报错
以上两个系统都是在软路由上全新安装的官方系统
都能 ping通 服务器域名
客户端配置文件相同

openwrt 报错提示
[ERRO] [error:CRYPTO_ERROR (0x12a): x509: certificate signed by unknown authority]

### 服务端安装信息或者一键脚本信息

hysteria-linux-amd64 v1.2

### VPS 信息

单核 512M 单IPv4  有域名

### 服务端配置

{
  "listen": ":12345",
  "protocol": "udp",
  "acme": {
    "domains": [
      "123.123.com"
    ],
    "email": "666@666.com"
  },
  "auth": {
    "mode": "passwords",
    "config": ["12345"]
  },
  "resolver": "udp://1.1.1.1:53",
  "resolve_preference": "4"
}

### 服务端日志

openwrt上运行客户端时，服务端无日志

### 客户端安装信息

hysteria-linux-386 v1.2

### 客户端配置

{
  "server": "123.123.com:12345",
  "up_mbps": 3,
  "down_mbps": 4,
  "socks5": {
    "listen": "0.0.0.0:1080"
   },
  "auth_str": "12345"
}

### 客户端运行环境（操作系统）

 Debian11 x64 ；OpenWRT19.07 x86

### 客户端日志

启动时 报错
[ERRO] [error:CRYPTO_ERROR (0x12a): x509: certificate signed by unknown authority]

**Comment by mritd** [comment]
尝试一下 `opkg install ca-certificates` 然后重新启动

**Comment by rankaiyx** [comment]
> 尝试一下 `opkg install ca-certificates` 然后重新启动

谢谢！解决了，就是这个原因。我也怀疑是缺了相关外部包，只是不知道包名，建议在配置说明或常见问题里备注一下

**Comment by mritd** [comment]
这东西跟 hysteria 没有任何关系, 标准发行版都会预装的; 如果不装那么你这个设备上的标准程序将没法请求 HTTPS 地址(除非忽略证书验证或者内置 CA 库).

**Comment by rankaiyx** [comment]
> 这东西跟 hysteria 没有任何关系, 标准发行版都会预装的; 如果不装那么你这个设备上的标准程序将没法请求 HTTPS 地址(除非忽略证书验证或者内置 CA 库).

嗯 可能是因为openwrt特别注重rom  所以官方原生系统未预装这个包  算是发行版里的一个特例
