### ISSUE TITLE
关于单线程速率疑问

### ISSUE THREAD

**Issue by f4nff** [HyNetwork/hysteria#425]
### 功能描述

<img width="623" alt="image" src="https://user-images.githubusercontent.com/19538878/188257059-82578f4b-aa99-45b4-944b-46a9d759b668.png">

`iperf3 -c de2sk.72mb.xyz -R -u -b 300M`

测速单线程跑300M没啥问题，
为什么tcp单线程下载最高也就是100MBps

起码也得250Mbps左右吧？

### 这个功能的必要性

按道理说，iperf3 测速udp单线程300MBps，
hysteria 开销那么大，性能吃掉小二百兆的开销？

**Comment by f4nff** [comment]
通过tun模式，
下面机子测速为
<img width="370" alt="image" src="https://user-images.githubusercontent.com/19538878/188257165-7703daa5-7b5c-4d96-8eea-2054565b0ede.png">

**Comment by f4nff** [comment]
根据测速，chrome确实有性能问题，
然后我使用curl测速，结果跟iperf3结果相当，
但是如果不采用hy，得到udp传输速率近300MBps，使用hy之后，速率只有175MBps，

**Comment by f4nff** [comment]
```
{
"server": "152.197.64.73:12346", 
  "protocol": "udp",
  "up_mbps": 30,
  "down_mbps": 300,
  "retry": -1, 
  "retry_interval": 1,
"http": {
    "listen": "0.0.0.0:8080", 
    "timeout": 300 

  },
  "tun": {
    "name": "tun0",
	"timeout": 60,
    "persist": false

  },
  "relay_tcps": [
    {
      "listen": "0.0.0.0:531", 
      "remote": "1.1.1.1:53", 
      "timeout": 60 
    }
  ],
   "relay_udps": [
    {
      "listen": "0.0.0.0:531", 
      "remote": "8.8.8.8:53",
      "timeout": 60 
    }
  ],
	
	
	"server_name": "1-courier.push.apple.com", 
	"insecure": true, 
	"recv_window_conn": 671088640, 
	"recv_window": 671088640, 
	"disable_mtu_discovery": false

}
```

**Comment by f4nff** [comment]
尝试使用最新版本编译：
client：
```

  "tun": {
    "name": "tun0",
	"timeout": 60,
    "mtu": 1500, // MTU 值
    "tcp_sndbuf": "8m", // TCP 发送 buffer 大小 (字符串，如 4096, 4k, 2m)
    "tcp_rcvbuf": "8m", // TCP 接收 buffer 大小 (字符串，如 4096, 4k, 2m)
    "tcp_autotuning": true, // 启用 TCP 接收 buffer 自动调整
    "persist": false,
  },

	
	"server_name": "1-courier.push.apple.com", 
	"insecure": true, 
	"recv_window_conn": 671088640, 
	"recv_window": 671088640, 
	"disable_mtu_discovery": false

```

server：

```
{
	"listen": ":12346",
	"cert": "./my.crt",
	"key": "./my.key",
	"up_mbps": 300,
	"down_mbps": 300,
	"recv_window_conn": 671088640, 
	"recv_window_client": 671088640, 
	"max_conn_client": 65535
}
```

速率大幅提升。

**Comment by flyhigao** [comment]
> 尝试使用最新版本编译： client：
> 
> ```
> 
>   "tun": {
>     "name": "tun0",
> 	"timeout": 60,
>     "mtu": 1500, // MTU 值
>     "tcp_sndbuf": "8m", // TCP 发送 buffer 大小 (字符串，如 4096, 4k, 2m)
>     "tcp_rcvbuf": "8m", // TCP 接收 buffer 大小 (字符串，如 4096, 4k, 2m)
>     "tcp_autotuning": true, // 启用 TCP 接收 buffer 自动调整
>     "persist": false,
>   },
> 
> 	
> 	"server_name": "1-courier.push.apple.com", 
> 	"insecure": true, 
> 	"recv_window_conn": 671088640, 
> 	"recv_window": 671088640, 
> 	"disable_mtu_discovery": false
> ```
> 
> server：
> 
> ```
> {
> 	"listen": ":12346",
> 	"cert": "./my.crt",
> 	"key": "./my.key",
> 	"up_mbps": 300,
> 	"down_mbps": 300,
> 	"recv_window_conn": 671088640, 
> 	"recv_window_client": 671088640, 
> 	"max_conn_client": 65535
> }
> ```
> 
> 速率大幅提升。

提升到什么程度？
