### ISSUE TITLE
[请求帮助] 在使用 caddy 生成的证书时无法启动 hysteria 服务

### ISSUE THREAD

**Issue by wclmgcd** [HyNetwork/hysteria#429]
### 问题详情

systemctl start hysteria-server 命令无法启动，而用/usr/local/bin/hysteria -c /etc/hysteria/config.json server 可正常启动
systemctl status hysteria-server错误如下：
● hysteria-server.service - Hysteria, a feature-packed network utility optimized for networks of poor quality
     Loaded: loaded (/lib/systemd/system/hysteria-server.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-09-06 09:53:04 CEST; 5s ago
       Docs: https://github.com/HyNetwork/hysteria/wiki
    Process: 949 ExecStart=/usr/local/bin/hysteria -c /etc/hysteria/config.json server (code=exited, status=1/FAILURE)
   Main PID: 949 (code=exited, status=1/FAILURE)

Sep 06 09:53:04 wuceyi.com systemd[1]: Started Hysteria, a feature-packed network utility optimized for networks of poor quality.
Sep 06 09:53:04 wuceyi.com hysteria[949]: 2022-09-06T09:53:04+02:00 [INFO] [config:{Listen::42107 Protocol:faketcp ACME:{Domains:[] Email: DisableHTTPChallenge:false DisableTLS>
Sep 06 09:53:04 wuceyi.com hysteria[949]: 2022-09-06T09:53:04+02:00 [FATA] [error:open /etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/www.xxxxxxxx.tk/www.xxxxxxxx.tk.crt: permi>
Sep 06 09:53:04 wuceyi.com systemd[1]: hysteria-server.service: Main process exited, code=exited, status=1/FAILURE
Sep 06 09:53:04 wuceyi.com systemd[1]: hysteria-server.service: Failed with result 'exit-code'.
lines 1-12/12 (END)

config.json配置
{
  "listen": ":47063",
  "protocol": "faketcp",
  "cert": "/etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/www.xxxxxxxx.tk/www.xxxxxxxx.tk.crt",
  "key": "/etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/www.xxxxxxxx.tk/www.xxxxxxxx.tk.key",
  "obfs": "xxxxxxxxxxxxxx",
  "auth": {
        "mode": "password",
	"config": {
	"password": "xxxxxxxxxxxxxxxxx"
	}
            },
  "alpn": "h3",
  "up_mbps": 87,
  "down_mbps": 112
}

hysteria-server是脚本自动生成：
[Unit]
Description=Hysteria, a feature-packed network utility optimized for networks of poor quality
Documentation=https://github.com/HyNetwork/hysteria/wiki
After=network.target

[Service]
User=hysteria
CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_NET_RAW
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_NET_RAW
NoNewPrivileges=true
WorkingDirectory=/etc/hysteria
Environment=HYSTERIA_LOG_LEVEL=info
ExecStart=/usr/local/bin/hysteria -c /etc/hysteria/config.json server
Restart=on-failure
RestartPreventExitStatus=1
RestartSec=5

[Install]
WantedBy=multi-user.target

### 服务端安装信息或者一键脚本信息

hysteria version v1.2.0 2022-08-14T01:56:17.587Z 944c0ecf646324c0151b026a55752c23378b909c

### VPS 信息

virtono 

### 服务端配置

{
  "listen": ":47063",
  "protocol": "faketcp",
  "cert": "/etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/www.xxxxxxxx.tk/www.xxxxxxxx.tk.crt",
  "key": "/etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/www.xxxxxxxx.tk/www.xxxxxxxx.tk.key",
  "obfs": "xxxxxxxxxxxxxx",
  "auth": {
        "mode": "password",
	"config": {
	"password": "xxxxxxxxxxxxxxxxx"
	}
            },
  "alpn": "h3",
  "up_mbps": 87,
  "down_mbps": 112
}

### 服务端日志

● hysteria-server.service - Hysteria, a feature-packed network utility optimized for networks of poor quality
     Loaded: loaded (/lib/systemd/system/hysteria-server.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-09-06 09:53:04 CEST; 5s ago
       Docs: https://github.com/HyNetwork/hysteria/wiki
    Process: 949 ExecStart=/usr/local/bin/hysteria -c /etc/hysteria/config.json server (code=exited, status=1/FAILURE)
   Main PID: 949 (code=exited, status=1/FAILURE)

Sep 06 09:53:04 wuceyi.com systemd[1]: Started Hysteria, a feature-packed network utility optimized for networks of poor quality.
Sep 06 09:53:04 wuceyi.com hysteria[949]: 2022-09-06T09:53:04+02:00 [INFO] [config:{Listen::42107 Protocol:faketcp ACME:{Domains:[] Email: DisableHTTPChallenge:false DisableTLS>
Sep 06 09:53:04 wuceyi.com hysteria[949]: 2022-09-06T09:53:04+02:00 [FATA] [error:open /etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/www.xxxxxxxx.tk/www.xxxxxxxx.tk.crt: permi>
Sep 06 09:53:04 wuceyi.com systemd[1]: hysteria-server.service: Main process exited, code=exited, status=1/FAILURE
Sep 06 09:53:04 wuceyi.com systemd[1]: hysteria-server.service: Failed with result 'exit-code'.
lines 1-12/12 (END)

### 客户端安装信息

无

### 客户端配置

无

### 客户端运行环境（操作系统）

无

### 客户端日志

无

**Comment by haruue** [comment]
你试图让 hysteria 使用 caddy 的证书， 但是 hysteria 是用专门的用户运行的， 这个用户没有权限访问 caddy 的证书。
```
Sep 06 09:53:04 wuceyi.com hysteria[949]: 2022-09-06T09:53:04+02:00 [FATA] [error:open /etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/www.xxxxxxxx.tk/www.xxxxxxxx.tk.crt: permi>
```

为了解决这个问题， 你可以用 root 或者用 caddy 用户\* 运行 hysteria 。

\*注意： 运行 caddy 的用户不一定总是叫做 `caddy`， 有些系统可能使用 `wwwdata` 或者 `http` 来运行 caddy， 你可以使用 `ls -l /etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/www.xxxxxxxx.tk/www.xxxxxxxx.tk.crt` 来对文件的属主进行确认。

执行下面的命令
```sh
systemctl edit hysteria-server.service
```

根据 systemd 自动生成的英文提示， 在有效的位置填入下面的内容
```ini
[Unit]
User=caddy
Group=caddy
```

保存文件并退出， 并重启 hysteria-server.service 服务。

**Comment by wclmgcd** [comment]
感谢大佬，成功解决

**Comment by daiaji** [comment]
我希望在caddy容器中重启hysteria容器。
然后情况就变得比较微妙。
https://github.com/mholt/caddy-events-exec
caddy有这种基于事件的钩子插件。
但现在容器中重启另外一个容器请起来还是很微妙。
