### ISSUE TITLE
支持IPV6入站后， 走nat64代理或者cf的warp

### ISSUE THREAD

**Issue by mmm8955405** [HyNetwork/hysteria#432]
### 功能描述

像：https://github.com/HyNetwork/hysteria/issues/261一样；
支持nat64 和 dns64 

### 这个功能的必要性

在只有IPV6的网络下，vps可以访问其他IPV4的网站

**Comment by mmm8955405** [comment]
![11](https://user-images.githubusercontent.com/5687907/189545722-ecbd8dad-da6b-4f74-a556-0a3aed308485.png)
目前IPV6客户端可以和服务端IPV6进行连接，但是服务端无法连接IPV4地址.     服务端已经配置DNS64, 可以ping 通IPV4网站

**Comment by mmm8955405** [comment]
服务端会尝试和对应域名的ipv4地址建立连接，能否直接是域名？
![11](https://user-images.githubusercontent.com/5687907/189546307-ab90020f-9e1d-406b-9496-3acdfcde4a5f.png)

**Comment by haruue** [comment]
你在客户端使用的是 TProxy/REDIRECT 或者 TUN 模式吗？

**Comment by mmm8955405** [comment]
这是我客户端的配置，服务端一样。 没有启用TProxy/REDIRECT 和 TUN模式
`{
    "server": "xxjj.xyz:36712",
    "protocol": "udp",
    "socks5": {
        "listen": "127.0.0.1:1080"
    },
    "http": {
        "listen": "127.0.0.1:8080"
    },
	"obfs": "ffffff",
    "up_mbps": 30,
    "down_mbps": 30
}`

**Comment by haruue** [comment]
客户端使用 socks 和 http 的 inbounds 的话， 直接在服务端配置加上下面这两个应该就能解决问题。。
```
"resolver": "udp://[2001:db8:xxxx::1]:53", // 改成你的 dns64 服务的地址
"resolve_preference": "6", // 配置仅 IPv6 解析
```

**Comment by mmm8955405** [comment]
> 客户端使用 socks 和 http 的 inbounds 的话， 直接在服务端配置加上下面这两个应该就能解决问题。。
> 
> ```
> "resolver": "udp://[2001:db8:xxxx::1]:53", // 改成你的 dns64 服务的地址
> "resolve_preference": "6", // 配置仅 IPv6 解析
> ```

可以了，感谢大佬！
