### ISSUE TITLE
长城宽带和Hysteria好配置？

### ISSUE THREAD

**Issue by alcatraz-zz** [HyNetwork/hysteria#433]
### Feature Details

Hi guys. I'm on crappy 长城宽带 and running verified certificates on the server, quic protocol.

I can't get Hysteria to work for longer than a few minutes before communication is zero for several hours. It's like the traffic is blocked.

Xray works fine all the time, but it's not as fast as Hysteria so I'd love to find out what would work better. 

On 电信 and 联通 Hysteria works great. I tried port numbers around 3xxxx and 5xxxx. 

So if 长城宽带 has an exception for port 443 traffic, what port could we try to use for Hysteria UDP?

中文回答也行！谢谢

### The necessity of this feature

...

**Comment by chika0801** [comment]
建议不要用长城宽带 即可

**Comment by alcatraz-zz** [comment]
> 建议不要用长城宽带 即可

😁 我还想找好好的办法。Hysteria应该能帮垃圾网的用户吧。

**Comment by alcatraz-zz** [comment]
I tried "Wechat-video" and "faketcp" too but those don't work at all even on 电信. Only QUIC works.

**Comment by haruue** [comment]
> I tried "Wechat-video" and "faketcp" too but those don't work at all even on 电信. Only QUIC works.

应该不至于电信也用不了。。
注意如果客户端改了 `protocol` 选项， 服务端也要改成一样的。

**Comment by alcatraz-zz** [comment]
成功了！ udp 123 端口好用。 推荐👍

**Comment by alcatraz-zz** [comment]
Port 123 only works sometimes. It's like it becomes blocked at random times. I have to fall back on Xray most of the time. But the response time of Hysteria is MUCH better than Xray (probably because of UDP, right?). The delay is noticeably less.

If anyone knows of any good UDP ports (like TCP443) please let me know. I tried some gaming ports but no go.

Also, does anyone know if Hysteria might sometime become supported in V2rayNG (android app)? I feel that ClashMetaforAndroid is complicated to configure geoip on. On windows, V2rayN-HysteriaCore works well.

Thanks!

**Comment by cross-hello** [comment]
Sagernet[https://github.com/SagerNet/SagerNet] has supported hysteria.

----------------------------------------

*From: *alcatraz-zz ***@***.***>
*To: *HyNetwork/hysteria ***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Oct 26, 2022 10:48:26
*Subject: *Re: [HyNetwork/hysteria] 长城宽带和Hysteria好配置？ (Issue #433)

**Comment by alcatraz-zz** [comment]
I was so wrong this whole time. There's no problem using UDP on 长城宽带. The priblem was me using an expired certificate so I had to switch to allowinsecure=true. Hysteria kicks Xray's ass when it comes to responsiveness. Every request feels like it takes around half the time now.  Thumbs up to you guys!

Now my only problem is finding a good Android app for Hysteria. Sager seems bloated+overkill+unsupported  and ClashmetaforAndroid is great but a bit buggy. I hope V2rayNG adds support. Love that app.
