### ISSUE TITLE
[请求帮助] TProxy 模式下， IPv6 UDP 请求会导致客户端崩溃 error:unable to obtain original destination

### ISSUE THREAD

**Issue by xtccc** [HyNetwork/hysteria#435]
### 问题详情

ipv6透明代理开启， hysteria 报错退出
[FATA] [error:unable to obtain original destination: %!s(<nil>)] Client shutdown

### 服务端安装信息或者一键脚本信息

hysteria version v1.2.1 2022-09-10T01:25:46.128Z 03e397b152134419d0ed4cb0565328fd81bd29f7

### VPS 信息

aws

### 服务端配置

{
  "listen": ":36666",
  "cert": "/root/hysteria/fullchain.cer",
  "key": "/root/hysteria/hysteriaxxx.key",
  "auth": {
    "mode": "passwords",
    "config": [
      "xxxxx"
    ]
  },
   //"acl": "/etc/hysteria/my_list.acl",
    //"mmdb": "/etc/hysteria/GeoLite2-Country.mmdb",
      "recv_window_conn": 58982400,
  "recv_window_client": 235929600, 
  "protocol": "wechat-video"
}

### 服务端日志

Sep 15 14:30:01 xtccvps hysteria[340049]: 2022-09-15T14:30:01+08:00 [INFO] [src:[2408:xxxx]:48429] Client connected

### 客户端安装信息

hysteria version v1.2.1 2022-09-10T01:25:46.128Z 03e397b152134419d0ed4cb0565328fd81bd29f7

### 客户端配置

{
    "server": "[2605:xxxx]:36666",
    "server_name": "xxxx",
    "protocol": "wechat-video",
    "down_mbps": 380,
    "up_mbps": 30,
    "auth_str": "xxxxx",
    "retry": 100,
    "tproxy_tcp": {
    "listen": "0.0.0.0:60080", 
    "timeout": 300 
    },
    "tproxy_udp": {
    "listen": "0.0.0.0:60080", 
    "timeout": 300 
    }
}

### 客户端运行环境（操作系统）

archlinux

### 客户端日志

Sep 15 14:21:53 j1900 systemd[1]: Started Hysteria Client Service.
Sep 15 14:21:53 j1900 hysteria[1380]: 2022-09-15T14:21:53+08:00 [INFO] [config:{Server:[2605:xxxx]:36666 Protocol:wechat-video Up: UpMbps:30 Down: DownMbps:380 Retry:100 RetryInterval:0 SOCKS5:{Listen: >
Sep 15 14:21:54 j1900 hysteria[1380]: 2022-09-15T14:21:54+08:00 [INFO] [addr:[2605:xxxx]:36666] Connected
Sep 15 14:21:54 j1900 hysteria[1380]: 2022-09-15T14:21:54+08:00 [INFO] [addr:0.0.0.0:60080] UDP TProxy up and running
Sep 15 14:21:54 j1900 hysteria[1380]: 2022-09-15T14:21:54+08:00 [INFO] [addr:0.0.0.0:60080] TCP TProxy up and running
Sep 15 14:21:57 j1900 hysteria[1380]: 2022-09-15T14:21:57+08:00 [FATA] [error:unable to obtain original destination: %!s(<nil>)] Client shutdown
Sep 15 14:21:57 j1900 systemd[1]: hy.service: Main process exited, code=exited, status=1/FAILURE
Sep 15 14:21:57 j1900 systemd[1]: hy.service: Failed with result 'exit-code'.

**Comment by haruue** [comment]
记得遇到过这个问题， `tproxy_tcp` 和 `tproxy_udp` 的 `listen` 填 `:60080` 能解决么？

**Comment by haruue** [comment]
之前有人问过这个问题， 但是当时我没能复现。。
#382 
既然你用的是 Arch Linux， 能发一下 `iptables-save` 和 `ip6tables-save` 的输出， 以及 `ip rule` 和 `ip -6 rule` 的输出么？ 我复现一下。

**Comment by xtccc** [comment]
> 之前有人问过这个问题， 但是当时我没能复现。。 #382 既然你用的是 Arch Linux， 能发一下 `iptables-save` 和 `ip6tables-save` 的输出， 以及 `ip rule` 和 `ip -6 rule` 的输出么？ 我复现一下。
晚上吧，路由器掉线了，连不上了， 等我晚上回家再弄吧

**Comment by xtccc** [comment]
注意这些日志是.tar.xz压缩包， github不让传.xz我就加了后缀.txt

[log_435.tar.xz.txt](https://github.com/HyNetwork/hysteria/files/9574835/log_435.tar.xz.txt)

**Comment by xtccc** [comment]
牛的，修好了
```
/usr/bin/hysteria -v
hysteria version Unknown 20220916181941 e67f2d6c7e4d978d4f8a90a3d4bc83c2cbd43cfb
Sep 16 18:24:20 j1900 hysteria[84981]: 2022-09-16T18:24:20+08:00 [INFO] [addr:0.0.0.0:60080] UDP TProxy up and running
Sep 16 18:24:20 j1900 hysteria[84981]: 2022-09-16T18:24:20+08:00 [INFO] [addr:0.0.0.0:8088] HTTP server up and running
Sep 16 18:24:20 j1900 hysteria[84981]: 2022-09-16T18:24:20+08:00 [INFO] [addr:0.0.0.0:60080] TCP TProxy up and running
```
```
❯ curl -6svL www.google.com |more
*   Trying 2607:f8b0:4007:815::2004:80...
* Connected to www.google.com (2607:f8b0:4007:815::2004) port 80 (#0)
> GET / HTTP/1.1
> Host: www.google.com
> User-Agent: curl/7.85.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Fri, 16 Sep 2022 10:25:07 GMT
< Expires: -1
< Cache-Control: private, max-age=0
< Content-Type: text/html; charset=ISO-8859-1
< P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
< Server: gws
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< Set-Cookie: 1P_JAR=2022-09-16-10; expires=Sun, 16-Oct-2022 10:25:07 GMT; path=/; domain=.google.com; Secure
< Set-Cookie: AEC=AakniGNZyJcr4WZZ-79P9Rqvqrcsv8Q-wFTdeTq9xbclhRvTslCAFcbrasQ; expires=Wed, 15-Mar-2023 10:25:07 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
< Set-Cookie: NID=511=kbywwLORS8EVmyubWR1tL_-bi9yuYXv4r3evHqP5VSjwhRI-4A85OpQmGcPrM89UfVBrzpo1DkkDFe6k68PW1irDy2HkZhFFC3iTehU-ENL_XBdWebMqZ1AVJxfaU08jQMYR1HnhZN_RFWjlgqahsVOZsuFPMD9Yq4xyZS7FWVI; expires=Sat, 18-Mar-2023 10:25:07 GMT; path=/; domain=.google.com; HttpOnly
< Accept-Ranges: none
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< 
{ [520 bytes data]
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world's in
```
