### ISSUE TITLE
[请求帮助] ACL文件去哪里下载

### ISSUE THREAD

**Issue by caodaye** [HyNetwork/hysteria#437]
### 问题详情

[0mClient configuration loaded
2022-09-17T01:02:55+08:00[31m [FATA] [file:acl/routes.acl] [error:open acl/routes.acl: The system cannot find the path specified.] [0mFailed to parse ACL

ACL文件去哪里下载，之前使用的是hihysteria_cmd_0.3a版本，一直使用到现在。下载了1.2.1版本的hysteria-windows-amd64.exe，文件夹中只有hysteria-windows-amd64.exe和新建的config.json，运行就提示ACL这个报错。

### 服务端安装信息或者一键脚本信息

bash <(curl -fsSL https://git.io/hysteria.sh)

### VPS 信息

日本东京 3C4G

### 服务端配置

{

"protocol": "wechat-video",
"up_mbps": 12500,
"down_mbps": 12500,
"http": {
"listen": "127.0.0.1:10809",
"timeout" : 300,
"disable_udp": false
},
"socks5": {
"listen": "127.0.0.1:10808",
"timeout": 300,
"disable_udp": false
},
"alpn": "h3",
"acl": "acl/routes.acl",
"mmdb": "acl/Country.mmdb",
"auth_str": "",
"server_name": "wechat.com",
"insecure": true,
"recv_window_conn": 655360000,
"recv_window": 2621440000,
"disable_mtu_discovery": true,
"resolver": "https://223.5.5.5:443/dns-query",
"retry": 3,
"retry_interval": 3
}

### 服务端日志

服务器端没任何问题。

### 客户端安装信息

hysteria version v1.2.1 2022-09-10T01:25:46.128Z 03e397b152134419d0ed4cb0565328fd81bd29f7

### 客户端配置

{

"protocol": "wechat-video",
"up_mbps": 12500,
"down_mbps": 12500,
"http": {
"listen": "127.0.0.1:10809",
"timeout" : 300,
"disable_udp": false
},
"socks5": {
"listen": "127.0.0.1:10808",
"timeout": 300,
"disable_udp": false
},
"alpn": "h3",
"acl": "acl/routes.acl",
"mmdb": "acl/Country.mmdb",
"auth_str": "",
"server_name": "wechat.com",
"insecure": true,
"recv_window_conn": 655360000,
"recv_window": 2621440000,
"disable_mtu_discovery": true,
"resolver": "https://223.5.5.5:443/dns-query",
"retry": 3,
"retry_interval": 3
}

### 客户端运行环境（操作系统）

w11

### 客户端日志

[0mClient configuration loaded
2022-09-17T01:02:55+08:00[31m [FATA] [file:acl/routes.acl] [error:open acl/routes.acl: The system cannot find the path specified.] [0mFailed to parse ACL

**Comment by haruue** [comment]
如果你不需要使用 ACL 功能， 只需删除配置文件中的 `"acl": "acl/routes.acl",` 这行即可。
如需获得 ACL 使用帮助请参考 https://github.com/HyNetwork/hysteria/wiki/%E5%85%B3%E4%BA%8E-ACL

**Comment by Satan023** [comment]
离谱，这么重要的信息为什么不写到guide里，我找了半天怎么让hysteria用v2ray的路由不用acl....
