### ISSUE TITLE
[请求帮助] 兄弟们有没有更新过最新版本后不能用wechat-video协议的呢 udp是可以的

### ISSUE THREAD

**Issue by idavailable** [HyNetwork/hysteria#438]
### 问题详情

用的emptysuns的hihy脚本 更新过最新版本后不能用wechat协议 可以用udp 

### 服务端安装信息或者一键脚本信息

hihy

### VPS 信息

cc 512内存1核心 2t流量小鸡

### 服务端配置

无

### 服务端日志

没有日志

### 客户端安装信息

cmd 运行

### 客户端配置

无

### 客户端运行环境（操作系统）

win10

### 客户端日志

也没有

**Comment by idavailable** [comment]
服务器端出现 显示no recent network activity

**Comment by haruue** [comment]
开 obfs 了没？ 客户端版本和服务端版本保持一致试试？

**Comment by idavailable** [comment]
没开 只用了fuckmetillthedaylight 那个 c和s都是1.2.1最新的
