### ISSUE TITLE
[FATA] [error:invalid syntax] Failed to set resolver

### ISSUE THREAD

**Issue by isaac574** [HyNetwork/hysteria#440]
用上新版本的hysteria-linux-amd64  V1.2.1, 出现以上错误.

**Comment by haruue** [comment]
在之前， `resolver` 这个配置项目支持 `1.1.1.1:53` 这种格式。
现在该格式已经不再支持， 你可以写
1. `udp://1.1.1.1:53` 指定协议和端口
2. `1.1.1.1` 只指定 IP ， 等价于 `udp://1.1.1.1:53` （默认 UDP 53 端口）。
