### ISSUE TITLE
关于降低CPU占用率

### ISSUE THREAD

**Issue by koolca** [HyNetwork/hysteria#445]
### 功能描述

试用一段时间感觉Hysteria非常优秀，但我VPS性能较弱，运行服务端，经过测试，带宽到300Mbps时CPU占用率100%，有没有办法降低CPU占用率？
目前开启了faketcp，关闭了obfs，"alpn": "h3"

### 这个功能的必要性

VPS的硬件AES加速能用得上吗？

**Comment by chika0801** [comment]
没有办法，路由器上建议你限制下行到160Mbps以内试试

**Comment by koolca** [comment]
好的，感谢
