### ISSUE TITLE
[Feature Request] Do not exit if network is not ready.

### ISSUE THREAD

**Issue by suienzan** [HyNetwork/hysteria#451]
### Feature Details

Do not exit if network is not ready.

### The necessity of this feature

When start hysteria before network is ready, hysteria will exit.

In condition where network cannot be started synchronously on boot, hysteria as service will failed and need manual start.

**Comment by haruue** [comment]
Did you try specify `"retry": -1`?

**Comment by haruue** [comment]
Closed due to lack of information.
Feel free to reopen it if this issue is not solved by `"retry": -1`.

**Comment by suienzan** [comment]
Solved
