### ISSUE TITLE
[Fatal issue] A 设备使用 faketcp 协议运行 hysteria 客户端并监听端口，B 设备使用此端口连接并进行 speedtest.net 测速会导致 A 设备彻底断网。

### ISSUE THREAD

**Issue by yjmp14** [HyNetwork/hysteria#454]
例：A 设备 ip 为 192.168.1.2，使用 faketcp 协议运行 hysteria，监听 socks5 端口 1080；B 设备 ip 为 192.168.1.3，在 B 浏览器上设置 socks5 代理 192.168.1.2:1080，然后使用 speedtest.net 进行测速，测速进行 1~2 次后，A 设备彻底断网，因我使用的 A 是无头设备，断网后 ssh 无法连接故无法查看具体情况，只能断电重启恢复网络。

更致命的问题：如 A 设备连接的路由器为单臂路由*，进行上述连接、测速操作后，该路由器会发生彻底断网，无论有线、Wifi 设备均无法访问包括路由器管理页面在内的任何网络，只能断电重启恢复网络。

*注：适用于任何路由器最简单的单臂路由设置方法：路由器 WAN 口连接路由器 LAN 口，路由器另一个 LAN 口连接光猫 LAN 口，光猫设置桥接，使用路由器拨号，此时光猫的 LAN 口、Wifi 以及路由器的 LAN 口、Wifi 都能上网。

**Comment by haruue** [comment]
你的 A 设备是什么配置？
有没有一种可能是内存占用过多， 系统炸了， 而不仅仅是断网……

**Comment by yjmp14** [comment]
> 你的 A 设备是什么配置？ 有没有一种可能是内存占用过多， 系统炸了， 而不仅仅是断网……

A 设备是 1G 内存的树莓派，确实有可能内存占用过多系统炸了，不过我没有显示器只能通过 ssh 访问所以不好确认。

另外在单臂路由的情况下还会导致路由器网络断了/系统炸了有点难以理解，路由器固件为 3.4 内核的 Padavan。

**Comment by haruue** [comment]
如果实际上的故障是发生在路由器上， 那么比较大的概率是路由器而不是 Hysteria 的 bug。

我没有能刷 Padavan 固件的路由器， 要调试这个问题不太容易。

要不试试看另一个更加通用的 udp2raw 实现？ 会不会有类似的问题。
https://github.com/wangyu-/udp2raw
你可以把 hysteria client 和 hysteria server 都跑在 udp 模式， 然后套这个 udp2raw 的 faketcp 模式来转发 hysteria 的 udp 端口。
也就是像下面这样
```
hysteria-client <==udp==> udp2raw-client <==faketcp==> udp2raw-server <==udp==> hysteria-server
```
在 hysteria 内建 udp2raw 支持之前， 就是用这个方法来做 faketcp 的。

**Comment by hujiao80** [comment]
我也观察到类似的问题，不同的是我碰到的是只要用v2aryN的测试服务器速度功能一、两次后hysteria的线路就会断线5分钟左右。

使用环境：通过passwall的socks配置功能将几条hysteria的线路转为了本地的socks代理，然后将这几个socks代理做为passwall的Frontend线路，这么做的目的是为了把不同配置的线路都能用来一起负载均衡。同时在电脑上的v2rayN也配置了“路由器IP:socks端口”这样的线路做为本地代理使用。

问题现象：当在v2rayN上对这几条socks代理进行测试服务器速度数次后基本都会出现线路断线的问题，此时再测速的话v2rayN提示“the request returned with HTTP status code ServiceUnavailable”，在路由器haproxy的监控页面也可以看到几条线路都下线了，大概在5分钟左右会逐渐恢复。

目前测试过多个openwrt、passwall的版本，faketcp、udp、套udp2raw各种方式均尝试过，都会复现同样的现象，而用同样的配置方法将vless、trojan线路转为socks代理似平并没有同样的现象，实在是无法判断到底是passwall还是hysteria的问题了。

**Comment by yjmp14** [comment]
经后续测试，认为确实可能是路由器的bug，在使用网线连接 WAN LAN 口的方式做单臂路由时，只要拔掉这条网线网络就能恢复，无需断电重启路由器。issue 先关了，后续如有变化再更新。

**Comment by yjmp14** [comment]
进一步测试基本确定问题出在树莓派内核参数 net.core.rmem_max 默认值过小，将该值调大即可。
