### ISSUE TITLE
[功能请求] 希望能增加个把日志输出到文件的功能, 类似*ray那种

### ISSUE THREAD

**Issue by wutongskype** [HyNetwork/hysteria#460]
### 功能描述

1.希望能增加个把日志输出到文件的功能, 类似*ray那种 access / error 分开记录
2.增加一个客户端连不上服务器就自动退出HY进程的功能, 也可以尝试几次, 还是无法跟服务器通信 就自动退出. 最好是个开关. 参考这里: https://github.com/HyNetwork/hysteria/discussions/420#discussioncomment-3509544

### 这个功能的必要性

1.方便弄个nginx这种http程序看日志, 不然每次寄了以后都要ssh进vps小鸡打命令才能看日志,着实有点麻烦哈
2.HY可以作为客户端,配合systemd守护进程, 最后和Haproxy搞负载均衡.

### 当前可用的替代方案

1.不太清楚, 没搞明白现在HY如何输出日志...
2.目前俺写了个脚本, 但是检测起来不太准

**Comment by haruue** [comment]
> 希望能增加个把日志输出到文件的功能, 类似*ray那种 access / error 分开记录
既然你在用 systemd ， 这个可以用 systemd 的 `StandardOutput=` 和 `StandardError=` 实现， 具体可参照 [`systemd.exec(5)`](https://man.archlinux.org/man/core/systemd/systemd.exec.5.en)

> 增加一个客户端连不上服务器就自动退出HY进程的功能, 也可以尝试几次, 还是无法跟服务器通信
1. 如果你是希望在客户端启动的时候， 连不上服务器就自动退出， 那你可以删除客户端配置文件里的 `"retry"` 选项， 默认就不重试。
2. 如果你是希望在客户端正常运行的时候， 与服务器失去连接时自动退出， 这个功能已经实现为 #421 并且将在下一版本发布。
