### ISSUE TITLE
[Feature Request] 对于心跳增加一个判断

### ISSUE THREAD

**Issue by f4nff** [HyNetwork/hysteria#462]
### Feature Details

心跳设置一个值，超过这个值，就主动断开，重新发起请求。

### The necessity of this feature

<img width="598" alt="image" src="https://user-images.githubusercontent.com/19538878/195492125-b8543a7f-b8b4-4efb-8b6d-7ce2c1ebb534.png">

存在一种情况，
发起请求之后，这个连接是没有速度的，
必须强制断开，重新发起请求，才有速度。

<img width="572" alt="image" src="https://user-images.githubusercontent.com/19538878/195492247-b55370c3-50b7-4577-8781-c19ffbbd368a.png">

如果不判断，就会导致一种类似假死的情况。

虽然是小概率，但是十分影响体验。

**Comment by liuxyon** [comment]
这就是我之前说的断流..

**Comment by f4nff** [comment]
但是貌似有点不好判断呢，

**Comment by koolca** [comment]
确实有断流存在，但不是完全不能连通，而是速度变慢。此时杀掉客户端进程重启，速度又能上去。可能与客户端偶尔有大量连接不能正常关闭有关，我现在改了代码手动关闭连接，已经稳定跑了几天没有再遇到相同的状况，但不能确定问题就解决了。附上我改动的地方，有遇到相同问题的同学可以测试一下（我不是软件从业者，代码可能有问题，谨慎尝试）。文件是pkg/transport/client.go
`var lastTCPConn *faketcp.TCPConn
var lastUDPConn *net.UDPConn

func (ct *ClientTransport) quicPacketConn(proto string, server string, obfs obfsPkg.Obfuscator) (net.PacketConn, error) {
        if len(proto) == 0 || proto == "udp" {
                conn, err := net.ListenUDP("udp", nil)
                if err != nil {
                        return nil, err
                }
        defer func() {
                    if lastUDPConn != nil {
                lastUDPConn.Close()
            }
                    lastUDPConn = conn
            }()
                if obfs != nil {
                        oc := udp.NewObfsUDPConn(conn, obfs)
                        return oc, nil
                } else {
                        return conn, nil
                }
        } else if proto == "wechat-video" {
                conn, err := net.ListenUDP("udp", nil)
                if err != nil {
                        return nil, err
                }
        defer func() {
                    if lastUDPConn != nil {
                lastUDPConn.Close()
            }
                    lastUDPConn = conn
            }()
                if obfs == nil {
                        obfs = obfsPkg.NewDummyObfuscator()
                }
                return wechat.NewObfsWeChatUDPConn(conn, obfs), nil
        } else if proto == "faketcp" {
                var conn *faketcp.TCPConn
                conn, err := faketcp.Dial("tcp", server)
                if err != nil {
                        return nil, err
                }
        defer func() {
                    if lastTCPConn != nil {
                lastTCPConn.Close()
            }
                    lastTCPConn = conn
            }()
                if obfs != nil {
                        oc := faketcp.NewObfsFakeTCPConn(conn, obfs)
                        return oc, nil
                } else {
                        return conn, nil
                }
        } else {
                return nil, fmt.Errorf("unsupported protocol: %s", proto)
        }
}`

**Comment by f4nff** [comment]
静待楼上测试反馈效果，

**Comment by koolca** [comment]
自用几天没出现问题，以上只是给遇到偶尔断流或速度下降的同学一个临时解决办法，使用风险自担

**Comment by f4nff** [comment]
@koolca 

把 pkg/transport/client.go
这个修改后的文件直接上传上来，

**Comment by koolca** [comment]
[client.zip](https://github.com/HyNetwork/hysteria/files/9805716/client.zip)
需要解压

**Comment by f4nff** [comment]
我也编译挂上看看。

**Comment by liuxyon** [comment]
> 以上只是给遇到偶尔断流或速度下降的同学一个临时解决办法，使用风险自担

我遇到的断流情况是完全没有速度,不只是慢的问题. 断开重新连接后恢复速度.

**Comment by mailsex** [comment]
> [client.zip](https://github.com/HyNetwork/hysteria/files/9805716/client.zip) 需要解压

可以把编译好的程序发一下吗 ，我不会编译。。

**Comment by koolca** [comment]
> > [client.zip](https://github.com/HyNetwork/hysteria/files/9805716/client.zip) 需要解压
> 
> 可以把编译好的程序发一下吗 ，我不会编译。。

最新的1.2.2版本好像已经修复连接不能正常关闭的bug了，更新到最新的版本即可

**Comment by mailsex** [comment]
> > > [client.zip](https://github.com/HyNetwork/hysteria/files/9805716/client.zip) 需要解压
> > 
> > 
> > 可以把编译好的程序发一下吗 ，我不会编译。。
> 
> 最新的1.2.2版本好像已经修复连接不能正常关闭的bug了，更新到最新的版本即可

嗯嗯，正在尝试。谢谢。

**Comment by f4nff** [comment]
## 1.2.2

- Fix a bug where the client would crash for IPv6 UDP requests in TProxy mode.
- Fix a bug where the client did not release old UDP sockets when reconnecting.
- Fix a bug where using DoT (DNS over TLS) as resolver would cause the client/server to crash.
- Add `quit_on_disconnect`, `handshake_timeout`, `idle_timeout` options to client config.
- Drop server's legacy protocol (v2) support.
- Updated quic-go to v0.30.0, small performance improvements.
