### ISSUE TITLE
[Help me] After upgraded to v1.2.1 the server side doesn't start anymore.

### ISSUE THREAD

**Issue by glamoroussky** [HyNetwork/hysteria#468]
### Details

Ever since I use the official bash file to update Hysteria to v1.2.1, the application is not starting anymore.
All the config are the same as previous.

### Server-side hysteria or scripts information

hysteria version v1.2.1 2022-09-10T01:25:46.128Z 03e397b152134419d0ed4cb0565328fd81bd29f7

### VPS information

Oracle, X86 Intel, 1GB, Ubuntu 20.04

### Server-side configuration

{
  "listen": ":xxx",
  "protocol": "udp",
  "cert": "/etc/letsencrypt/live/xxx/fullchain.pem",
  "key": "/etc/letsencrypt/live/xxx/privkey.pem",
  "up_mbps": 15,
  "down_mbps": 25,
  "obfs": "xxx",
  "auth": {
    "mode": "passwords",
    "config": ["xxx"]
  },
  "alpn": "h3",
  "recv_window_conn": 15728640,
  "recv_window_client": 67108864,
  "resolver": "tls://1.1.1.1:853"
}

### Server-side logs

 Loaded: loaded (/lib/systemd/system/hysteria-server.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2022-10-19 14:52:08 UTC; 4s ago
       Docs: https://github.com/HyNetwork/hysteria/wiki
    Process: 2540 ExecStart=/usr/local/bin/hysteria -c /etc/hysteria/config.json server (code=exited, status=2)
   Main PID: 2540 (code=exited, status=2)
        CPU: 13ms

### Client-side hysteria information

N/A

### Client-side configuration

N/A

### Client-side environment (operating system)

N/A

### Client-side logs

N/A

**Comment by haruue** [comment]
Please use `journalctl -e -u hysteria-server.service` to check the server log.

**Comment by glamoroussky** [comment]
> Please use `journalctl -e -u hysteria-server.service` to check the server log.

panic: runtime error: invalid memory address or nil pointer dereference
Oct 20 11:47:55 hysteria[74996]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0xd180ff]
Oct 20 11:47:55 hysteria[74996]: goroutine 1 [running]:
Oct 20 11:47:55 hysteria[74996]: github.com/folbricht/routedns.NewDoTClient({0xf7c2ee, 0x3}, {0xc00014467e, 0xb}, {{0xc000281080, 0x7}, {0x0, 0x>
Oct 20 11:47:55 hysteria[74996]:         /go/pkg/mod/github.com/folbricht/routedns@v0.1.6-0.20220806202012-361f5b35b4c3/dotclient.go:59 +0x1bf
Oct 20 11:47:55 hysteria[74996]: main.setResolver({0xc000144678, 0x11})
Oct 20 11:47:55 hysteria[74996]:         /github/workspace/cmd/resolver.go:85 +0x731
Oct 20 11:47:55 hysteria[74996]: main.server(0xc00018b180)
Oct 20 11:47:55 hysteria[74996]:         /github/workspace/cmd/server.go:32 +0x12f
Oct 20 11:47:55 hysteria[74996]: main.glob..func5(0x17f1380?, {0xf7ce05?, 0x2?, 0x2?})
Oct 20 11:47:55 hysteria[74996]:         /github/workspace/cmd/main.go:139 +0x395
Oct 20 11:47:55 hysteria[74996]: github.com/spf13/cobra.(*Command).execute(0x17f1380, {0xc000141480, 0x2, 0x2})
Oct 20 11:47:55 hysteria[74996]:         /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
Oct 20 11:47:55 hysteria[74996]: github.com/spf13/cobra.(*Command).ExecuteC(0x17f0e80)
Oct 20 11:47:55 hysteria[74996]:         /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
Oct 20 11:47:55 hysteria[74996]: github.com/spf13/cobra.(*Command).Execute(...)
Oct 20 11:47:55 hysteria[74996]:         /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
Oct 20 11:47:55 hysteria[74996]: main.main()
Oct 20 11:47:55 hysteria[74996]:         /github/workspace/cmd/main.go:205 +0x25

**Comment by glamoroussky** [comment]
hysteria-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 20 11:47:55 systemd[1]: hysteria-server.service: Failed with result 'exit-code'.

**Comment by tobyxdd** [comment]
Thanks for the feedback. Fixed in f92c2cd
