### ISSUE TITLE
长城宽带hysteria配置

### ISSUE THREAD

**Issue by alcatraz-zz** [HyNetwork/hysteria#475]
你好，目前用xray和hysteria。Hysteria很好用但有时长城宽带好像封udp端口。以前长城宽带不稳定但现在xray比较好用。晚上8-9点还可以稳定看1080p60hz的youtube。之前这是不可能的。只是我发现hysteria+udp是比xray反应更速好很多了。有没有用户发现个好hysteria长城宽带的配置？推荐试哪一个端口数？谢谢帮助啊

**Comment by Smallthing** [comment]
指望长城不限制UDP，简直是。。
你用udp转伪tcp，如果还不行，换宽带

**Comment by alcatraz-zz** [comment]
I was so wrong this whole time. There's no problem using UDP on 长城宽带. The problem was me using an expired certificate so I had to switch to allowinsecure=true. Hysteria kicks Xray's ass when it comes to responsiveness. Every request feels like it takes around half the time now.  Thumbs up to you guys!

Now my only problem is finding a good Android app for Hysteria. Sager seems bloated+overkill+unsupported  and ClashmetaforAndroid is great but a bit buggy. I hope V2rayNG adds support. Love that app.

**Comment by tobyxdd** [comment]
You may also try https://github.com/MatsuriDayo/Matsuri which is a fork of SagerNet but I've heard its support for hysteria is more active.
