### ISSUE TITLE
[功能请求] hy这个更新检查能否做个开关关闭掉哈?

### ISSUE THREAD

**Issue by wutongskype** [HyNetwork/hysteria#476]
### 功能描述

hy这个更新检查能否做个开关关闭掉哈?
路由器上查看连接有个莫名其妙的连接出国...
![image](https://user-images.githubusercontent.com/40192806/198747581-c53a1b5b-35e6-4ffa-9656-1186c074927b.png)

### 这个功能的必要性

1 感觉有点尴尬
2 有漏(暴)电(露)的可能...

### 当前可用的替代方案

无

### 补充

无

**Comment by haruue** [comment]
更新检查目前可以只能通过命令行选项和环境变量关闭。 也就是以下 任意一种 方式。
+ 在启动 hysteria 的命令行参数里添加 `--no-check`
+ 在启动 hysteria 时设置环境变量 `HYSTERIA_NO_CHECK_UPDATE=1`
+ 在启动 hysteria 时设置环境变量 `HYSTERIA_NO_CHECK=1`
