### ISSUE TITLE
PC端  Google翻译失败

### ISSUE THREAD

**Issue by ultrastar663** [HyNetwork/hysteria#478]
### Details

手机端可以正常使用Google翻译，

PC端: v2rayn , HY协议，显示：

[INFO] [dst:translate.googleapis.com:443] [error:dial tcp 142.250.204.138:443: i/o timeout]

### Hysteria server information

hysteria-windows-amd64

### VPS information

正常

### Server config

正常

### Server logs

正常

### Hysteria client information

正常

### Client config

{
"server": "www.XXXX.top:32184",
"protocol": "wechat-video",
"up_mbps": 250,
"down_mbps": 250,
"http": {
"listen": "127.0.0.1:10809",
"timeout" : 300,
"disable_udp": false
},
"socks5": {
"listen": "127.0.0.1:10808",
"timeout": 300,
"disable_udp": false
},
"alpn": "h3",
"acl": "acl/routes.acl",
"mmdb": "acl/Country.mmdb",
"auth_str": "8964",
"server_name": "www.XXXXX.top",
"insecure": false,
"recv_window_conn": 26214400,
"recv_window": 104857600,
"disable_mtu_discovery": true,
"resolver": "https://223.5.5.5:443/dns-query",
"retry": 3,
"retry_interval": 3
}

### Client environment (operating system)

Windows 11

### Client logs

[INFO] [dst:translate.googleapis.com:443] [error:dial tcp 142.250.204.138:443: i/o timeout]

**Comment by tobyxdd** [comment]
hysteria 和你的 vps 能否连上特定网站无关。

**Comment by ultrastar663** [comment]
已经自行解决，删除routes.acl 里原先的内容，新增：

proxy domain-suffix translate.google.cn
proxy domain-suffix translate.google.com
proxy domain-suffix translate.googleapis.com
proxy domain-suffix google.com
proxy domain-suffix googleapis.com
direct country cn
proxy all
