### ISSUE TITLE
[问题咨询] 请问Hysteria支持Nginx反代端口吗？

### ISSUE THREAD

**Issue by iKira** [HyNetwork/hysteria#479]
### 问题详情

请问Hysteria服务端配置文件中的 “listen”: ":36712", 可以写成这样吗 “listen”: "127.0.0.1:36712",

我想用Nginx前置监听443端口，通过stream模块upstream转发到36712端口。已经尝试这么做了，发现无法联通，请问Hysteria设计上就不支持这么使用吗？

### 服务端安装信息或者一键脚本信息

无

### VPS 信息

无

### 服务端配置

无

### 服务端日志

无

### 客户端安装信息

无

### 客户端配置

无

### 客户端运行环境（操作系统）

无

### 客户端日志

无

**Comment by haruue** [comment]
月经问题， 先看 Wiki
https://github.com/HyNetwork/hysteria/wiki/Hysteria-%E6%94%AF%E6%8C%81-CDN-%E5%8F%8D%E4%BB%A3%E5%90%97%EF%BC%9F
用 Nginx 反代本质上和 CDN 反代是一样的。 如果你要用 Nginx 反代， 请直接用 V2Ray+TLS+Websocket 这样的成熟方案。

**Comment by iKira** [comment]
> 

刚刚已经翻到另外一个issue看到答案了，thx~
