### ISSUE TITLE
[Help me] It's even slower than shadowsocks

### ISSUE THREAD

**Issue by nathan-deng-ai** [HyNetwork/hysteria#486]
### Details

Hysteria:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/99947149/200212495-5b7c22d9-0698-4c2c-a6e4-09bd5b8d9ab9.png">

Shadowsocks:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/99947149/200212510-38523cb3-e84d-4480-83bf-67a5cdfc9ce2.png">

I was surprised by this speed difference, I thought that hysteria should be faster than shadowsocks

### Hysteria server information

hysteria version v1.2.2 2022-10-23T23:55:39.647Z 3d54cb43afab6bb700a35ef77b5436af5587470a

### VPS information

20G KVM - CN2 GIA ECOMMERCE
Location: JP - Equinix Osaka Softbank (JPOS_1)

### Server config

{
"listen":":443",
"protocol":"wechat-video",
"acme":{
"domains":["****"],
"email":"****",
},
"obfs":"****"
}

### Server logs

nothing special

### Hysteria client information

hysteria version v1.2.2 2022-10-23T23:55:39.647Z 3d54cb43afab6bb700a35ef77b5436af5587470a

### Client config

nothing special

### Client environment (operating system)

macOS 13 build 22A380

### Client logs

nothing special

**Comment by haruue** [comment]
Please provide the completed server & client config even if there is nothing special. I have VPS in the same region & with the same transit.

**Comment by haruue** [comment]
Closed due to lack of information to reproduce this issue.
