### ISSUE TITLE
[FATA] [error:listen udp 127.0.0.1:10800: set socket option: IPV6_TRANSPARENT: protocol not available]

### ISSUE THREAD

**Issue by yjmp14** [HyNetwork/hysteria#487]
v1.2.2 版本启动报错：
`[FATA] [error:listen udp 127.0.0.1:10800: set socket option: IPV6_TRANSPARENT: protocol not available]`

v1.2.1 版本无此问题。

配置有关部分（**服务器地址为 ipv6**）：
```
"tproxy_tcp": {
    "listen": "127.0.0.1:10800",
    "timeout": 300
},
"tproxy_udp": {
    "listen": "127.0.0.1:10800",
    "timeout": 60
},
```

**Comment by haruue** [comment]
配置改成下面这样呢？ 就是删除掉 listen 里面的 `127.0.0.1`
```
"tproxy_tcp": {
    "listen": ":10800",
    "timeout": 300
},
"tproxy_udp": {
    "listen": ":10800",
    "timeout": 60
},
```

**Comment by haruue** [comment]
如果问题仍然存在， 麻烦提供一下你的内核版本号（可以通过 `uname -r` 取得）， 以及 `/proc/config.gz` 或者 `/boot/config-<你使用的内核版本>` （如果存在的话）。

**Comment by yjmp14** [comment]
> 配置改成下面这样呢？ 就是删除掉 listen 里面的 `127.0.0.1`
> 
> ```
> "tproxy_tcp": {
>     "listen": ":10800",
>     "timeout": 300
> },
> "tproxy_udp": {
>     "listen": ":10800",
>     "timeout": 60
> },
> ```

该层这样可以了，谢谢！
