### ISSUE TITLE
TUN mode

### ISSUE THREAD

**Issue by tobyxdd** [HyNetwork/hysteria#64]

**Comment by tobyxdd** [comment]
![image](https://user-images.githubusercontent.com/1414953/117533453-ca168100-afa1-11eb-84cc-666607023990.png)

@felixding 你在 Twitter 上把我 block 了，所以很抱歉，这个项目不欢迎你，请你自觉停止使用

**Comment by luckypoem** [comment]
hi.
既然是TUN mode，如何用来搭建vpn?

**Comment by tobyxdd** [comment]
> hi.
> 既然是TUN mode，如何用来搭建vpn?

配置好开启 tun mode 以后添加路由到 tun 设备即可。后面我会考虑写个教程

**Comment by luckypoem** [comment]
hi.
期待教程早日问世。问世后，麻烦在此通知一下，非常感谢。

**Comment by cfcboy** [comment]
> > hi.
> > 既然是TUN mode，如何用来搭建vpn?
> 
> 配置好开启 tun mode 以后添加路由到 tun 设备即可。后面我会考虑写个教程

大佬，一年了，能写给教程吗。谢谢。
