### ISSUE TITLE
反代支持

### ISSUE THREAD

**Issue by Cat7373** [HyNetwork/hysteria#73]
例如服务器已有网站和合法证书，挂在 Nginx 后面，那么如何在 Nginx 上新增域名或挂到已有域名的特定路径后面呢？

注：Nginx 已支持 HTTP/3

如未支持建议添加，如已支持建议文档说明

**Comment by tobyxdd** [comment]
Nginx 不支持 HTTP/3 的 upstream，所以不支持也无法支持

**Comment by Cat7373** [comment]
1. 我是说任意支持 HTTP/3 的反代后面的支持
2. 添加 `--with-http_v3_module` 编译后，添加 `listen 443 http3 reuseport;` 即可在 443 端口(标准端口) 支持 HTTP/3

**Comment by tobyxdd** [comment]
据我所知目前 Nginx, Apache, Caddy 等没有一个支持 HTTP/3 **upstream** 回源，因此你说的这个 我这边实现了也无法测试和部署。如果你发现有其他支持的，或者这些里面哪个加入了支持可以随时告诉我。

Nginx 的 `http_v3_module`  是对客户端的支持，和我们在讨论的不是一码事
