### ISSUE TITLE
Client timeout issue

### ISSUE THREAD

**Issue by hdid** [HyNetwork/hysteria#88]
Hi
Sometimes client gives timeout and can not process the requests and i have to restart the client to works again.
I can not see any reason and logs are something like "...:443] [action:Proxy] SOCKS5 TCP request".
Also i applied sysctl recommends but the issue still exists.

**Comment by tobyxdd** [comment]
What do you mean by "gives timeout", is it stuck and unable to accept any new connections? What does the server log look like at this point?

**Comment by hdid** [comment]
The client does not respond to socks requests and time out occurs. On server; first time I saw "_[error:listen udp :0: socket: too many open files] UDP error_" so I checked ulimit and increased it to higher value. Next time I could see "_[error:Timeout: No recent network activity] UDP error_" but no one could resolve the issue.

**Comment by hdid** [comment]
The client does not respond to socks requests and time out occurs. On server; first time I saw "_[error:listen udp :0: socket: too many open files] UDP error_" so I checked ulimit and increased it to higher value. Next time I could see "_[error:Timeout: No recent network activity] UDP error_".

**Comment by tobyxdd** [comment]
The latest update should have fixed this. Mind giving it a try again?
