### ISSUE TITLE
HTTP authentication  不工作

### ISSUE THREAD

**Issue by molezz** [HyNetwork/hysteria#89]
如下设置后， 客户端浏览器不管密码输入不输入都可以连接访问 ， 密码随便输也可以连接。
0.8.1版本
chrome+switchyomega， 设置http代理
```
  "http": {
    "listen": "0.0.0.0:8080", 
    "user": "me",
    "password": "xxx343"
  }
```

**Comment by tobyxdd** [comment]
![image](https://user-images.githubusercontent.com/1414953/119430558-dc90fa00-bcc5-11eb-9677-0727dc3a6c98.png)

相同的 Hysteria 版本、配置，相同的 chrome+switchyomega，我没能复现。方便发下客户端完整日志么？

**Comment by molezz** [comment]
![image](https://user-images.githubusercontent.com/695412/119434342-9467eb00-bd4a-11eb-9a0e-b7caf5b6c808.png)

真的是奇怪，重新启动下客户端，密码用户名留空， 访问仍通。 难道是我将ca证书导入到本地了？

**Comment by molezz** [comment]
找到问题了， 原来未设置过密码，可以连通， 然后在config加了密码， 可能缓存了。
换了一个端口， 就弹出密码框了
