### ISSUE TITLE
连接不上服务器

### ISSUE THREAD

**Issue by luckypoem** [HyNetwork/hysteria#97]
yudeMacBook-Air:hysteria_darwin_amd64 brite$ ./cmd proxy client -config config.json
2021/07/06 10:47:56 Configuration error: no SOCKS5 listen address
yudeMacBook-Air:hysteria_darwin_amd64 brite$ ~/hysteria_darwin_amd64/hysteria_darwin_amd64/cmd proxy client -server mydomain.com:36710 -socks5-addr localhost:2080 -up-mbps 10 -down-mbps 50
2021/07/06 10:48:14 Configuration loaded: {SOCKS5Addr:localhost:2080 SOCKS5Timeout:0 ACLFile: ServerAddr:mydomain.com:36710 Username: Password: Insecure:false CustomCAFile: UpMbps:10 DownMbps:50 ReceiveWindowConn:0 ReceiveWindow:0 Obfs:}

2021/07/06 10:48:26 Client initialization failed: NO_ERROR: Handshake did not complete in time
yudeMacBook-Air:hysteria_darwin_amd64 brite$ cat config.json
{
  "server": "mydomain.com:36710",
  "up_mbps": 10,
  "down_mbps": 50,
  "socks5": {
    "listen": "127.0.0.1:2080"
  },
  "http": {
    "listen": "127.0.0.1:2081"
  }
}
yudeMacBook-Air:hysteria_darwin_amd64 brite$

怎么解决？

**Comment by luckypoem** [comment]
服务器端是在运行中的。我用命令ps aux|grep hysteria看到了hysteria的进程

**Comment by tobyxdd** [comment]
你这个是什么时候的版本了？现在的 CLI 参数早就不是这样用的了
